### ISSUE TITLE
Tracking things to do in the 6.0 release

### ISSUE THREAD

**Issue by marijnh** [codemirror/CodeMirror#2898]
Split the core into modules

Remove deprecated features:
- The vimMode option
- (Skim over the manual to see what else is no longer useful)

Change the defineOption interface, get rid of CodeMirror.Init

New model of keymaps
- Declarative, no longer treat them as objects that can be modified at any time
- Split options like fallthrough from the actual binding properties

**Comment by marijnh** [comment]
(This is now the 6.0 release, since 5.0 was used for releasing the mobile support.)

**Comment by marijnh** [comment]
Add an `instance.addon` object in which addons can store their states. (Rather than abusing `instance.state` for this.)

**Comment by mightyguava** [comment]
I'd like to change the vim keymap defineOption interface as well, and potentially merge it with the core editor's defineOption. The interface is a bit different right now because vim mode options have instance values that fall back to global values. The option values are also potentially not stored by vim but by whomever defines the option (See https://github.com/codemirror/CodeMirror/pull/3200)... Haven't thought very hard on what a better interface would be nor if it's reasonable to merge with the core editor's defineOption either.

**Comment by foo123** [comment]
Helo Marijnh, i would like to suggest a few options

(check the [codemirror-grammar add-on](https://github.com/foo123/codemirror-grammar) as well)

1. make `electricChars` accept a variable/dynamic input (this is already achieved by `electricInput` option as far as i can tell)
2. Pass current `line number` on to the current highlight mode
3. A way for mode to determine if it is on `first line of code` or `last line of code` (important when some `code` can only be placed only on first line, or first non-empty line but not elsewhere and so on..) This information is already available in `Codemirror`, just pass it on to the current mode (does not break anything as far as i can tell, while extremely useful for highlighting)

Best

**Comment by adrianheine** [comment]
I think this issue is no longer relevant, since CodeMirror 6 is going to be a complete rewrite. We are currently raising money for this work: See [the announcement](https://codemirror.net/6/) for more information about the rewrite and a demo.
