### ISSUE TITLE
Cursor in RTL should move up when clicking right at line start

### ISSUE THREAD

**Issue by pablopla** [codemirror/CodeMirror#2927]
I suggest to set rtlMoveVisually to true in the bidi demo.

When moving the cursor right in the beginning of a line, the cursor should move up instead of down.
To reproduce:
Set direction to "rtl" and rtlMoveVisually to true.
In a new line write RTL letter like א.
Press the right arrow twice.
The cursor should go up one line but instead goes one line down.

**Comment by jasonzhao3** [comment]
Hi @marijnh,  It seems there are still issues with rtl support, such as the mouse cursor and the first space when you typed in the rtl mode. Is there any plan to fix this soon? I'm now integrating codemirror to our code base to replace the old rangy-based highlighter. The cursor really drives me crazy. 

Also, since you have done lots of work, could you share some thoughts about where the problem may be and how difficult it is to fix it? I can also join you to debug this. :)

**Comment by marijnh** [comment]
@jasonzhao3 The `direction` branch was never properly finished, and I haven't been able to allocate the time needed to finish and land it. Bidi/RTL stuff is always very subtle and debugging it takes me, as a non-RTL-language-speaker, ages. The way people could help is by

- Providing test cases
- Rebasing the `direction` branch onto the current code (lots of conflicts, I expect)
- Figuring out what some of the more obscure code in the `direction` branch, which was not written by me, is trying to do (and adding more tests to ensure it continues doing what it should do)
- Or, alternatively, hire me to do this work

**Comment by adrianheine** [comment]
This should be much better in master since #4463 is merged. Please open new issues for specific problems, and I'll have a look :)
