### ISSUE TITLE
CodeMirror.indentLine does not correctly on block(s) with a leading `.`

### ISSUE THREAD

**Issue by Mark-Simulacrum** [codemirror/CodeMirror#3015]
When I use `CodeMirror.indentLine(lineNo)`, I would expect the following expected/current to happen. As shown, the `.then` block isn't currently indented. I think that it should be, and if not by default, at least under an option.

Current:
```js
promise
.then(function (result) {
  // ...
});
```

Expected:
```js
promise
  .then(function (result) {
    // ...
  });
```

----

I've tested this in `Brackets`, the editor, but I believe this to be a universal flaw, not specific to the Brackets environment.

Please tell me if you need any more information.

**Comment by marijnh** [comment]
Attached patch will cause the `.then` line to be indented, but it won't indent the whole function body. This is more or less by design, since I prefer the style of indentation that makes a statement's block end align with its start. If you really want the exact style you showed, I'd be open to a pull request that adds a mode option for that.
