### ISSUE TITLE
Show pointer cursor while hovering over a selection

### ISSUE THREAD

**Issue by MarcelGerber** [codemirror/CodeMirror#3020]
(https://github.com/adobe/brackets/pull/9584)
On Windows at least, [almost all code editors](https://github.com/adobe/brackets/pull/9584#issuecomment-66663831) show a [pointer cursor](http://helpdeskgeek.com/wp-content/pictures/2012/05/mouse-cursor-jumps.jpeg) (`cursor: default`) while hovering a selection when Drag & Drop is enabled.
We wanted to have the same behavior in Brackets and [tried it by styling `.CodeMirror-selected` on Windows](https://github.com/adobe/brackets/pull/9584/files#diff-2), but we're facing some issues:
* The cursor constantly switches between pointer and caret while dragging a selection (https://github.com/adobe/brackets/pull/9584#issuecomment-67715608)
* The cursor sometimes doesn't change at all, for some reason (https://github.com/adobe/brackets/pull/9584#issuecomment-67840203)

Thus, imho there should be an option in CodeMirror directly to show the pointer cursor while hovering a selection.

**Comment by marijnh** [comment]
Use the `markselection` addon to also add a class (`CodeMirror-selectedtext` by default) to the selected text, and then (also) add the `pointer` rule to that class.

**Comment by MarcelGerber** [comment]
We tried this too (https://github.com/MarcelGerber/brackets/commit/5791e609cbcfa910c05cbc5374c749a8f2016308), but we had issues with this as well:
* The cursor constantly switches between pointer and caret while dragging a selection (adobe/brackets#9584 (comment)) (same as above)
* The pointer cursor doesn't show up while hovering the end-of-line whitespace of a selection that continues to the next line
  ![image](https://cloud.githubusercontent.com/assets/2641501/5630015/302bcfda-95ba-11e4-84ae-fcbc0836bda3.png)

**Comment by marijnh** [comment]
> The cursor constantly switches between pointer and caret while dragging a selection 

Well, obviously styling the selection won't prevent the cursor for showing up differently when outside of the selection. You could try a hack where you set the cursor for the whole editor to pointer while the mouse button is down.

But the second point is a good one. Since the actual node under the cursor will be the `<pre>` for the current line, there's no sane way to use CSS to style the cursor in that case. What ACE appears to be doing is handling a "mousemove" event. You could write an addon that registers such a handler and, using `getClientRects`, figures out if the mouse is inside the selection every time it moves, and sets the editor's `cursor` style as appropriate.

**Comment by MarcelGerber** [comment]
I still think this is something that should be in main CodeMirror as, as pointed out above, almost every other editor (even ACE) does the same.

**Comment by marijnh** [comment]
Try with the new [`selection-pointer`](http://codemirror.net/doc/manual.html#addon_selection-pointer) addon.

**Comment by MarcelGerber** [comment]
Yeah, that's exactly what we need in Brackets. Thanks!
