### ISSUE TITLE
How wrap selections?

### ISSUE THREAD

**Issue by bernex** [codemirror/CodeMirror#3034]
I wanna wrap selected texts...

Selected `text` to `<a>text</a>`...

`replaceSelection` remove text, do not leave..

How to do it optimally? With multi-selection support. Thanks!

**Comment by marijnh** [comment]
You call `replaceRange` twice, once for each end of the selection (or ofter, when there are multiple selections). Take care to make your changes back-to-front, so that the addition of text does not make subsequent ranges invalid (i.e. if you first add the text in front of the selection, the end might no longer be where it used to be).

In any case, this is not a bug, so the issue tracker is the wrong place for it.
