### ISSUE TITLE
Wrong cursor pos after undo

### ISSUE THREAD

**Issue by MarcelGerber** [codemirror/CodeMirror#3035]
(https://github.com/adobe/brackets/issues/2805)

Steps:
Go to http://marcelgerber.github.io/github/demo/codemirror/wrong-undo.html and follow the steps

Result:
After undoing, the cursor is behind `random`

Expected:
After undoing, the selection is on `cloor` (which is what happens if you make the edits "by hand")

The demo is at https://github.com/codemirror/CodeMirror/commit/e53166be3207dd91a2ef60d2bc23862fe5f5d25d

**Comment by marijnh** [comment]
CodeMirror restores the selection after undo to where it was when the change was made. As such, this is expected behavior when you make changes through the API at a place away from the cursor. If you don't want it to behave in this way, a workaround would be to temporarily change the selection when making such changes.

**Comment by MarcelGerber** [comment]
Ah yeah, that makes sense (even though it's weird when the cursor jumps through the whole file) and your workaround seems to work.
Closing.
