### ISSUE TITLE
Mobile branch v4.12.1 linenumbers above 9 not displayed correctly on iOS/Safari

### ISSUE THREAD

**Issue by LukeArthurs** [codemirror/CodeMirror#3068]
I just got the latest mobile branch v.4.12.1 and tested on iOS 8.1.3 in Safari and the linenumbers above 9 are not displayed correctly. The digits are drawn on top of each other.
The latest master branch doesn't have this problem, but it still got the nasty cursor bug which isn't anymore on the mobile branch :) Both bugs are important to me and neither branch fixes both :(

Here a screenshot of the linenumber problem:
![img_0534](https://cloud.githubusercontent.com/assets/6594054/6050202/061a0d68-acbe-11e4-931a-3e2bb88dca10.png)

**Comment by marijnh** [comment]
I can't reproduce this issue (using iOS 8.1.3 as well) -- the line numbers show up fine for me. If you strip down your test case to just an editor, and remove extra CSS, does the problem still occur?

**Comment by DaveConroy** [comment]
This problem is present on iPad iOS 8 and Android 4.2.2 tablet on codemirror 5.0 when there is more than 99 rows as seen in this picture.
![codemirror](https://cloud.githubusercontent.com/assets/6907015/6464895/ad049aee-c1bd-11e4-97bd-94edb5ff1954.png)

Also note that at the two red arrows in the image the numbers go
10
10
So it appears that this is not just a styling issue as the number 10 (or could be 100 as the 0s could be on top of each other) is repeated twice.

This issue is also present on the codemirror website by just hitting backspace until you go past line 100 so it doesn't seem to be cause by our styling implementation.
http://codemirror.net/demo/marker.html

**Comment by zhangns** [comment]
I ran into the same problem in Android TextView using the master branch code (haven't tested with mobile branch yet), and fixed it with a css style.

.CodeMirror-gutter-elt {
    white-space: nowrap;
}

I think it *is* just a styling issue. "0" in "100" is wrapped to the next line and overlaps with "0" in "101", and the wrapped "1" in "101" overlaps with "0" in the "102" line, etc..

The problem doesn't occur in a desktop browser. I have no idea why ...

**Comment by marijnh** [comment]
I've managed to reproduce this. The line number gutter's width is automatically adjusted to fit the actual numbers' width, but it seems that in some cases on iOS a rounding error made the resulting elements too narrow. Attached patch adds an extra pixel to compensate for this, and for good measure also adds the `nowrap` rule. The problem is no longer showing up for me now.

**Comment by JanOonk** [comment]
I can also confirm that it's working fine now. Thanks.
