### ISSUE TITLE
Line numbers are off when collapsing a range starting at {line: 0, ch: 0}

### ISSUE THREAD

**Issue by Leonya** [codemirror/CodeMirror#3096]
When I do the following:

```
var startOffset = new CodeMirror.Pos(0, 0);
var endOffset = new CodeMirror.Pos(3, 0);

editor.markText(startOffset, endOffset, {
	collapsed: true
})
```

Line numbers on the gutter are as follows: 1, 5, 6,... while it should be 4, 5, 6...

CodeMirror 4.12

**Comment by marijnh** [comment]
This is by design. The collapsed marker starts on the first line, and part of the line it ends on is visible, so it shows the line number for the 1st line.

Do this instead:

    editor.markText({line: 0, ch: 0}, {line: 2}, {collapsed: true, inclusiveLeft: true, inclusiveRight: true})

That will make it impossible for the cursor to end up on the first three lines, and will cause the line numbers for those lines to be hidden.

**Comment by Leonya** [comment]
Oh, thanks.
