### ISSUE TITLE
"change" event fired asynchronously?

### ISSUE THREAD

**Issue by baoshan** [codemirror/CodeMirror#3120]
When `setRange` continuously inside a handler, the `change` events seemed to be aggregated and fired asynchronously.

Could someone clarify if it's by design?

The code

```
editor.on('change', function(){ console.log('change'); });

editor.on('cursorActivity', function(){
  console.log('setRange');
  editor.setRange('0', {line:0});
  console.log('setRange');
  editor.setRange('1', {line:0});
});
```

Outputs

```
setRange
setRange
change
change
```

Which was expected to be:

```
setRange
change
setRange
change
```

**Comment by marijnh** [comment]
`"change"` events (as well as `"cursorActivity"` and a number of other events) are fired at the end of the current [operation](http://codemirror.net/doc/manual.html#operation). That means that if you have a 'naked' call to `setRange`, which will start its own operation, you'll get your `"change"` handler called before the call to `setRange` returns. But if you are already in an operation (as in the case of the `"cursorActivity"` event in your example) the events are batched to the end of the operation. This is by design -- it is a way to ensure the editor is in a consistent state when event handlers are called.

**Comment by baoshan** [comment]
Thanks @marijnh for explaining the internal.

The `"changes"` event seems to be my rescue.
