### ISSUE TITLE
Right click (context menu) fires "blur" and "focus" events simultaneously 

### ISSUE THREAD

**Issue by aslushnikov** [codemirror/CodeMirror#3132]
Repro:

1. Goto http://codemirror.net/demo/complete.html
2. Add listeners to the editor instance:
  ```javascript
editor.on("blur", function() { console.log("BLUR"); })
editor.on("focus", function() { console.log("FOCUS"); })
  ```

3. do a right-click in the editor

Actual: a blur event is dispatched, immediately followed by "focus" event.
Expected: these events should not be dispatched at all for the right-click.

**Comment by marijnh** [comment]
This was caused by the right click (which isn't actually on the focused element, but which we can't `preventDefault` because we need it to open the context menu) briefly removing focus from the textarea. I've added a workaround which, in this case, simply holds off firing the blur event for a few milliseconds, and discards it entirely if the editor was refocused in the meantime.

**Comment by aslushnikov** [comment]
Thank you.
