### ISSUE TITLE
Show-hint on inputRead prevent popup showing when correct typo using backspace key

### ISSUE THREAD

**Issue by baoshan** [codemirror/CodeMirror#3162]
Suppose we're building an editor which shows hint on `inputRead` using `show-hint` and an asynchronous hint function (I guess the issue also exists on synchronously hint function):

1. When a user mistyped a keyword `functiom`, the hint function callback an empty list;
2. The `show-hint` add-on closed the `completionActive` I think;
3. The user use backspace to remove the end `m`, which is expected to show-hint again;
4. Since the `inputRead` event doesn't fire on backspace (I don't know the design decision here), the user doesn't get hint.

Please advice the suggested solution :)

**Comment by baoshan** [comment]
My intuition here was if the `inputRead` event is designed as an analogue to the `input` event on an `input` or `textarea` tag, that should also be fired on `backspace`.

Please correct me if `inputRead` is not an equivalent to `input`.

**Comment by marijnh** [comment]
`inputRead` intentionally has a different name from `input`. The two are not supposed to be equivalent. CodeMirror handles backspace through a keybinding, and text input through a completely different path. Only the code that takes typed text from the hidden textarea fires `inputRead`.

In this case, I think `show-hint` should not finally close the completion when an empty result is returned, so that you can backspace and have the widget automatically reopen. Attached patch implements this.
