### ISSUE TITLE
matchesonscrollbar slow with many matches

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#3173]
I've been trying to integrate the new find match highlighting addon internally and we've found the performance to be unacceptable when there is a large number of matches. We get ~900ms for the .redraw() call when there are 900 matches. Brief investigation into this suggests that it's coming from iteratively calling charCoords on all the matches, and so could be fixed by providing a batched version of that API.

**Comment by marijnh** [comment]
There is little to be gained from batching the `charCoords` API -- unless there are a lot of matches on a single line, there's not much repeated work. It might be possible, in a non-line-wrapping editor, to get a speedup from using line height info, instead of measuring individual characters. I'll give that a shot after Easter. (Tuesday)

**Comment by marijnh** [comment]
I actually had some time today. Patch 9f55603 (which depends on 1f3a196190) optimizes the measuring. It makes `redraw` about 23 times faster in my benchmark (which simply consists of annotating 1000 matches on a scrollbar). Does it have a similar effect in your use case?

**Comment by mtaran-google** [comment]
Yep, it seems to be sufficient to get good performance in the example I was using. Thanks!
