### ISSUE TITLE
Different behaviour in FF and Chromium with flexbox

### ISSUE THREAD

**Issue by vmx** [codemirror/CodeMirror#3231]
I'm using CodeMirror with a flexbox layout. I see differences between Firefox (39.0a2, 2015-04-29) and Chromium (41.0.2272.118), both on Debian. I can get it work properly with either of them, but not both at the same time.

Please see this minimal example and the comment in the CSS for more:
http://output.jsbin.com/vapudetemi/1/edit?css,output

**Comment by marijnh** [comment]
There is nothing in the CSS of the jsbin you linked.

**Comment by vmx** [comment]
I've updated the original comment to contain the correct link.

**Comment by marijnh** [comment]
That is interesting. This looks like a browser bug -- Chrome interpreting the `height: 100%` of the CodeMirror instance in a weird way. Even if I make `.item` have `position: relative`, the editor ends up too high. I don't have much experience with flexbox, but I don't think it is supposed to violate height calculation expectations like that. Even if I replace the editor instances with simply a div with class `CodeMirror`, the problem persists (the divs are the height of the outer element, rather than the inner ones).

**Comment by marijnh** [comment]
I am now getting even stranger behavior in Firefox. Closing this on the assumption that the browser are buggy and this isn't something CodeMirror itself can help (the issues show up even if CodeMirror is removed from the equation)
