### ISSUE TITLE
Can't get cursor last word in custom autocomplete (hint) 

### ISSUE THREAD

**Issue by paveliko** [codemirror/CodeMirror#3239]
Hey!
I'm trying to create autocomplete (intellisense) functionality on keyup event.
How can I get cursor last word as in example of anyword hint?

            var editor = CodeMirror.fromTextArea($textarea[0], {
                mode: 'text/x-pig',
                autofocus: true
            });

            editor.on('keyup', function(cm, event) {
                CodeMirror.showHint(cm, CodeMirror.hint.pig, {
                     completeSingle: true
                });
            });

            var list = expressionsService.getList();

            CodeMirror.registerHelper('hint', 'pig', function(cm, options) {

                var word = options.word;

                // word is undefined

                var cur = cm.getCursor(),
                    token = cm.getTokenAt(cur);
                return {
                    list: list,
                    from: CodeMirror.Pos(cur.line, token.start),
                    to: CodeMirror.Pos(cur.line, token.end)
                }

            });

**Comment by marijnh** [comment]
Firstly, this is not a bug report, so it does not belong here. Go to discuss.codemirror.net for support requests.

Don't use `keyup`, you can't rely on it being fired, since many key events will be `preventDefault`-ed when the editor handles them. You could listen for CodeMirror's `"inputRead"` event instead.
