### ISSUE TITLE
Selection problem in IE11, when leaving an iframe while selecting

### ISSUE THREAD

**Issue by mboehlke** [codemirror/CodeMirror#3261]
We found an issue with codemirror 5.2.0 (and previous).
We have a codemirror instance embedded in an iframe. 
While selecting some text with pressed left mousebutton and thereby unintentional leaving the iframe 
and release the mousebutton there: the selection of text occurres while mousemove and we found the 
only way to return to normal behaviour by clicking with the right button. 
We have created a minimal sample "EditorMan.html" with a left area outside an iframe on the right (see below). 
The misbehavior occurs with Win7 IE11.  (actual versions) 
It does not occur with Win7 FF and Chrome; and on OSX Safari.
Other combinations not tested. 
Despite that: Thank you for the great code.
Manuel 

The HTML file: EditorMan.htm
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta charset="utf-8" />
	<title>Editor MainView</title>

	<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function ()
		{
			document.getElementById("idRecipeCod").src = "Editor.htm";
		});
	</script>
</head>
<body>
	<div id=idLeft style="position:absolute; top:0; left:0; width:150px; bottom:0; background:beige">LEFT</div>
	<iframe id=idRecipeCod style="position:absolute; top:0; left:158px; right:0; bottom:0"></iframe>
</body>
</html>

The HTML file: Editor.htm
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta charset="utf-8"/>
		<title>Text Editor</title>

		<link rel="stylesheet" type="text/css" href="./codemirror/lib/codemirror.css" />

		<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
	    <script type="text/javascript" src="./codemirror/lib/codemirror.js"></script>

		<script type="text/javascript">
			$(document).ready(function () {
				var mycodemirror = CodeMirror(document.body, {
					value: "function myScript()\n{ var a = 1;\n var b = 42;\n return 100;\n}\n",
					mode: "javascript"
				});
			});
		</script> 
	</head>
	<body>
	</body>
</html>

**Comment by marijnh** [comment]
I am aware of this, but have not been able to come up with a solution.

- We normally rely on the `mouseup` event to abort a drag-select
- But when the mouse is released outside of the frame, that event isn't delived
- So on most browsers, we can use `event.which` to figure out whether the mouse is being held in a `mousemove` event.
- IE always sets `which` to 1, even if the button was released.
- It has a `buttons` property on such events, which could in theory be used to work around this.
- We did so for a while, but that caused problems as well, since there is a bug that causes this property to be reset to zero for no good reason if the DOM is updated during the drag (#2577).

Maybe the next IE (Spartan) will finally fix this. Until then, I think this bug is less of a problem than randomly having drag-select abort.

(Other solutions, if you can find one, are of course very welcome.)
