### ISSUE TITLE
Hanging Indent

### ISSUE THREAD

**Issue by mikagenic** [codemirror/CodeMirror#3263]
I've been trying to modify the indentwrap sample to create a hanging indent but no luck. 

What I'm trying to achieve is that for example for a line that  starts with a hyphen, when it wraps, the next (wrapped) line will indent under the first non space character _after_ the hyphen and not under the hyphen as in the sample.

Is this possible ? Can I get any pointers to implement this ?

Thanks!

**Comment by cben** [comment]
Working example: http://mathdown.net/?doc=demo-indentwrap
Code:
https://github.com/cben/mathdown/blob/428d6fe5a6cf54c9d4a8385cfced42079edcc323/mathdown.js#L151-L167

The indentation doesn't line up perfectly in my case because I'm generally
using a variable-width font,
and while I do style leading spaces and bullets to be fixed-width [1],
cm.defaultCharWidth() does not represent my fixed font, and I've been so
far too lazy to fix it...

[1]
https://github.com/cben/mathdown/blob/428d6fe5a6cf54c9d4a8385cfced42079edcc323/mathdown.js#L96-L114
     plus styling .cm-leadingspace, .cm-formatting-list,
.cm-formatting-quote in mathdown.css


2015-05-16 7:01 GMT+03:00 mikagenic <notifications@github.com>:

**Comment by marijnh** [comment]
Please don't open github issues for support requests. Use http://discuss.codemirror.net/ for that.

**Comment by mikagenic** [comment]
Sorry for that.

I opened a new discussion at http://discuss.codemirror.net/t/hanging-indent/243

cben can you please repost your answer there so I can comment on it ? (and thanks!)
