### ISSUE TITLE
Python operator recognized as keywords.

### ISSUE THREAD

**Issue by Carreau** [codemirror/CodeMirror#3266]
Some Python operator (`or`,`and` ) used to get the class `operator` and now get the class `keywords` which make it weird as they don't get the same color as other operator like `>`,`<=` ... etc.

**Comment by marijnh** [comment]
See the comment on patch 2e16ef661fd9a7261d143b23d22df87d3a75237c. @mtaran-google felt this was preferable, and I don't necessarily disagree (other modes, like JavaScript and clike, also highlight alphanumeric operators as keywords).
.

**Comment by Carreau** [comment]
Meh... I can see the use, but then that make every themes that define an operator style useless/inconsistent. 

What if I send a PR that change themes that don't have an `operator` style from `... .cm-keyword`  to `... .cm-keyword, ... cm-operator` ? That would still make operator visible, but leave freedom for theme that **want** to define a different operator style.

**Comment by marijnh** [comment]
> but then that make every themes that define an operator style useless/inconsistent.

That is a huge overstatement. Syntactically, keyword operators are also keywords, and highlighting them as such is hardly going to destroy the use of the highlighting.

Making all themes that don't specifically style operators style them as keywords is definitely not acceptable. You could make the Python mode style keyword operators as `"operator keyword"` if you want, so that it is up to the themes to determine which one has precedence.
