### ISSUE TITLE
Wrong indentation for Groovy closures with a return statement

### ISSUE THREAD

**Issue by jochenberger** [codemirror/CodeMirror#3276]
The Groovy mode produces the following indentation
```groovy
list.each {
  return
    }
```
If I add a semicolon, the indentation is correct:
```groovy
list.each {
  return;
}
 ```

**Comment by jochenberger** [comment]
It's also correct if I add a return value

**Comment by baconface** [comment]
I think CodeMirror is working correctly and the problem is your code.

Without seeing the rest of your code these recommendations may either be correct or wrong depending what you are wanting to achieve. If you really don't want to return a value and just do a return maybe try one of two options: ```return void``` which is like returning null or ```continue``` instead of returning nothing. Or you may want to return true or false. Either way using the return keyword is optional. However if you use return Groovy expects you to actually return something. In this case it looks like you are using return in order to break the each loop which is in itself not a recommended practice.

**Comment by marijnh** [comment]
Fixed in attached patch.

@baconface Declaring that a bug isn't a bug because the relevant code doesn't conform to your preferred coding style isn't really appropriate here. We try as much as possible to target language syntax, not specific coding styles.
