### ISSUE TITLE
new definition highlighting does more harm than good for C++

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#3332]
The clike C++ mode now highlights a wide variety of identifiers as blue "definitions". Try it for example with https://raw.githubusercontent.com/google/re2/master/re2/re2.cc. I think this approach may be a lost cause for C++ in particular without really beefing up the parser. For Java it seems to do the right thing much more. Would it be possible for that definition highlighting feature to only be enabled in certain language-specific instances of clike mode? Or could you at least provide an option so we can manually disable it for our (slightly custom) C++ mode?

**Comment by marijnh** [comment]
I assume you're talking about the way it tokenizes `x->y`? Attached patch fixes that. Are there other problems that you've noticed?

**Comment by mtaran-google** [comment]
The other problems I've noticed:
* in `namespace re2 {` `re2` is highlighted
* static method names in their declarations seem to be highlighted, but not the (more common) instance methods
* some initializations of variables like of `l` on line 240 and `fanout` on 279 get highlighted incorrectly

**Comment by marijnh** [comment]
Attached patch further improves the situation. Highlighting namespace names is intentional. I guess you both 'open' and 'define' a namespace with the same syntax, so you could argue whether calling it a definition is appropriate, but it seems sensible and harmless enough to do so.

I've also added a `styleDefs` option to the clike mode. You could, for example, say `CodeMirror.mimeModes["text/x-c++src"].styleDefs = false` to turn it off entirely. (Or define a new MIME with a copy of the old C++ config but with that option added.)
