### ISSUE TITLE
Does CodeMirror implement spell checking?

### ISSUE THREAD

**Issue by bobrocke** [codemirror/CodeMirror#3356]
is that an option to set somewhere, or should this be a feature request?

**Comment by marijnh** [comment]
The browser's built-in spell-check doesn't work with the way CodeMirror renders the content. You can integrate something like typo.js, by writing glue that uses `markText` to highlight suspected mistakes and hooking into mouse events to show a set of suggestions. Several people have done this but I'm not aware of an open-licensed implementation. This is out of scope for the main project, since the result is always going to be sub-optimal (big download, typo.js is often horribly slow) and I don't want to deal with the resulting support requests.

**Comment by williamstein** [comment]
On Thu, Jul 2, 2015 at 1:18 PM, Marijn Haverbeke <notifications@github.com>
wrote:

> The browser's built-in spell-check doesn't work with the way CodeMirror
> renders the content. You can integrate something like typo.js, by writing
> glue that uses markText to highlight suspected mistakes and hooking into
> mouse events to show a set of suggestions. Several people have done this
> but I'm not aware of an open-licensed implementation. This is out of scope
> for the main project, since the result is always going to be sub-optimal
> (big download, typo.js is often horribly slow) and I don't want to deal
> with the resulting support requests.
>
>
For what it is worth... In SageMathCloud (which is open source) spellcheck
runs a command on the backend server using ispell


https://github.com/sagemathinc/smc/blob/fc866b99e74297a3f4f748868680c5c35f2b9e8d/salvus/page/editor.coffee#L2492

then highlights all words that are not spelled correctly using a Codemirror
plugin:

https://github.com/sagemathinc/smc/blob/fc866b99e74297a3f4f748868680c5c35f2b9e8d/salvus/page/misc_page.coffee#L771



> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codemirror/CodeMirror/issues/3356#issuecomment-118154370>
> .
>



-- 
William (http://wstein.org)
