### ISSUE TITLE
Python long lists break syntax highlighting

### ISSUE THREAD

**Issue by drdhaval2785** [codemirror/CodeMirror#3443]
https://github.com/notepadqq/notepadqq/issues/139

There is a break in syntax highlighting for long python lists.
Firefox is the browser.

Details as per above link.

**Comment by marijnh** [comment]
Attached patch should help somewhat, though, since for performance reasons the editor doesn't highlight huge lines entirely, you might in some situations still see effects (such as when the long line opens a new block).

To get rid of this optimization entirely (but risk bad performance with long lines), you can set the `maxHighlightLength` option to `Infinity`.
