### ISSUE TITLE
Typing cursor (Caret) is always black - even on dark themes

### ISSUE THREAD

**Issue by melbourne2991** [codemirror/CodeMirror#3460]
I've implemented code mirror in a react app i'm building and have noticed that even when using dark themes (tested with Monokai and Paraiso-dark) the caret is black - which makes it very difficult to see. I've noticed in one of the examples using monokai on codemirror's project page that the caret is white so I take it this isn't the intended behavior - everything else appears to be working fine.

(the caret is to the right of the last closing curly bracket)
![screen shot 2015-08-20 at 12 02 25 pm](https://cloud.githubusercontent.com/assets/4619280/9373975/aadec702-4733-11e5-956e-81c244515e15.png)

````
	componentDidMount() {
		const refs = { ...this.refs }, props = { ...this.props };
		const codeEditorWrapper = React.findDOMNode(refs.codeEditorWrapper);

		this._codeMirrorInstance = CodeMirror(codeEditorWrapper, {
			value: props.value,
			mode: props.mode,
			theme: 'monokai',
			lineNumbers: true
		});
	}
````
using:  "codemirror": "^5.5.0"
tested on Chrome: Version 44.0.2403.155 (64-bit)

**Comment by marijnh** [comment]
The CSS selectors making the cursor white in dark themes are strictly more specific than the default black cursor style, so I am not sure how they could fail to apply. You'll have to use your browser's def tools to inspect the cursor element (`document.querySelector(".CodeMirror-cursor")`) to figure out what's going on and whether your styles might be interfering in some strange way.

Make sure you are using css files (for themes and basic codemirror.css) from a _single_ release. Using the current `codemirror.css` and older theme files might cause this, since the specificity of those rules was recently changed.

**Comment by rmullins9** [comment]
Hey melbourne2991 - I just came across this today when I updated the CSS for only the Monokai theme. It appears that the css that's on the codemirror site now no longer has !important on the class selector for .CodeMirror-cursor, which is probably what marijnh is referring to. This fixed it for me:

.cm-s-monokai .CodeMirror-cursor {border-left: 1px solid #f8f8f0 !important;}

(I'm using version 5.2)
