### ISSUE TITLE
Markdown multiline code incorroect highlighting

### ISSUE THREAD

**Issue by vimxts** [codemirror/CodeMirror#3463]
I've noticed a possible bug github fenced code and the 4 space indented code.

    - list
    
        code

    ```
    code
    ```

The above does not highlight the fenced `code` as **code** color, instead, it colors it black. Also, the indented code is highlighted with a list color.

![capture](https://cloud.githubusercontent.com/assets/5255292/9403953/ebbc11e0-481d-11e5-9dcc-f3bcd110cf6c.PNG)

**Comment by cben** [comment]
Not a bug.

The indented code is correctly colored - it's indented 4 spaces which is exactly how much list continuation lines should be indented.  It'd need 8 spaces to be parsed as code-inside-list.
[Some other markdown parsers allow less than 4 spaces for list continuation lines.  [CommonMark](http://spec.commonmark.org/0.21/#list-items) settled on using as much as the list marker + space after it — 2 in this case.  But in any case, all parsers I'm aware of would require 4 *extra* spaces for a code block (so 6 in this case).  [babelmark test](http://johnmacfarlane.net/babelmark2/?normalize=1&text=-+list%0A%0A++++code%0A%0A%60%60%60%0Acode%0A%60%60%60%0A) => no parser treats this as code inside list.]

The fenced code block is not recognized because you're using the bare `markdown` mode.  Fenced blocks (and a few more things) are supported by the [`gfm` mode](http://codemirror.net/mode/gfm/) built on top of the markdown mode.
