### ISSUE TITLE
Shift key issues in editor

### ISSUE THREAD

**Issue by cbaldwinweb** [codemirror/CodeMirror#3482]
Everytime I try to write a double quote the editor freezes and nothing happens. Nothing can happen I can't right click nothing, as if a eventListener kills everything. Is there a method or CodeMirror js file made for debugging these files? I've had lots of issues with the files altogether, as well as the default auto detect mode which I've deleted that right out of the code altogether. Any help would be greatly appreciated a well documented file, for the original unminified is not documented well enough.

**Comment by vincentwoo** [comment]
The original unminified CodeMirror files are fairly well documented. Can you reproduce the problem on any of the CM demo pages or in a JSFiddle? If not, we're probably not going to be able to help you. The issue is very likely on your end.

**Comment by cbaldwinweb** [comment]
No that is true, I can try to reproduce this on a fiddle or bin let me get everything together. And I'll comment back

**Comment by vincentwoo** [comment]
A couple things:

* We don't get pings if you update your comment. If you have new information, please add a new comment.
* Your writing is pretty manic. It's still not clear to me what "the issue" is, per se. Please try to state the smallest number of things we have to do to reproduce your issue. It would help a lot of you could create a fiddle or codepen with your problem, as well. As it stands I have to guess what you mean.

So, guessing:

Are you saying that if you include mode files in a particular order, and try to use a specific mode, the editor hangs on a quotation mark? The HTML mode absolutely does require that the XML mode be loaded first. HTML is a subset of XML. You can look at the demo HTML mode page's source code here: https://github.com/codemirror/CodeMirror/blob/master/demo/html5complete.html, where you will see that the XML mode is loaded prior to HTML mode:

```html
<script src=../lib/codemirror.js></script>
<script src=../mode/xml/xml.js></script>
<script src=../mode/javascript/javascript.js></script>
<script src=../mode/css/css.js></script>
<script src=../mode/htmlmixed/htmlmixed.js></script>
```

and if you examine the html mode itself: https://github.com/codemirror/CodeMirror/blob/master/mode/htmlmixed/htmlmixed.js, you'll see that it tries to require the XML mode.

`mod(require("../../lib/codemirror"), require("../xml/xml"), require("../javascript/javascript"), require("../css/css"));`

It also tries to require the JS and CSS modes, because HTML can embed arbitrary JS/CSS content, but I think those two are less critical to the functioning of the mode.

**Comment by cbaldwinweb** [comment]
Yes it was the order sorry I haven't really posted Issues on GitHub before. Also I've read the petite documentation, and neither of those require work for me I'm not using a subset language I'm using pure javascript for everything. And I have 6 or more languages I have to include so they are ready to go for the user. 

But like I said there should be an error handling process within the code to test if something that is required be loaded and if not give a log in the console or something. Just seems to me that it makes more since to handle the error before hand.

**Comment by vincentwoo** [comment]
The requires indicate what the JS file needs. On a browser, they do nothing and fall back to the regular case: `mod(CodeMirror);`.

I tried changing the order of the script tags, but everything still works fine for me. Please make a fiddle or codepen that demos the problem.

**Comment by cbaldwinweb** [comment]
Ok I will try, thanks for trying yourself I'll get it all sorted for you and post it in a new comment.

**Comment by chrisbaldwinj** [comment]
Issue happens here as well. Not sure why, It happens when I switch the mode to JavaScript and try to write `var a = ` freezes once I press <kbd>shift</kbd>+<kbd>'</kbd> to make a double quote.

After more testing it freezes on `~`, `"`, `'`, `/` these are the only keys I have found that it does it to. And it only does in when switching mode to Javascript and CSS so far. I have the following languages automatically loaded into the head in order as they appear.

* xml
* javascript
* css
* vbscript
* htmlmixed
* clike
* php
* sql

I kind of would like to know what would cause this. Maybe all the files included together, or the order, or some function overwriting each other. This has become a very big nuisance for me.

**Comment by vincentwoo** [comment]
Can you make a JSFiddle or CodePen that demonstrates the issue for us?

**Comment by chrisbaldwinj** [comment]
For some reason after using the minification helper it works. I'll do further testing and see what I can find, until then I guess close this. I tried making a fiddle and it didn't do the expected results. Cancelled all my external libraries I wrote all together and only had CodeMirror on and it still did it while not minified. So I guess back to square one on this.
