### ISSUE TITLE
Pure Markdown is matching fenced code blocks

### ISSUE THREAD

**Issue by WesCossick** [codemirror/CodeMirror#3533]
Test it out at http://codemirror.net/mode/markdown/

**Comment by marijnh** [comment]
Is this an actual problem for you, or just a non-conformance you noticed?

**Comment by WesCossick** [comment]
[SimpleMDE](https://github.com/NextStepWebs/simplemde-markdown-editor) just introduced a `parsingConfig` option that allows passing in CodeMirror mode configuration options, including `fencedCodeBlocks`. However, since CodeMirror parses fenced code blocks no matter what, it can't be disabled by setting `fencedCodeBlocks` to `false`.

**Comment by brondsem** [comment]
I think actually it isn't a fenced block being parsed in that case, but a multiline \`\` code span being parsed (which [is allowed](http://spec.commonmark.org/0.22/#code-spans)).  Visually they look similar because they are both code/comment lines.  But if you look at the parse state (e.g. by setting `highlightFormatting` on and checking the CSS classes) there is `cm-formatting cm-formatting-code cm-comment` for the first line of a \`\`\` section when `fencedCodeBlocks` is off, and when it is on it is `cm-formatting cm-formatting-code-block cm-comment`

The markdown mode does in fact check that fencedCodeBlocks is on before parsing for that.  I've looked at that recently for my PR #3496

I am not sure what to do about the end result of this though.  Perhaps figure out some way to style code blocks differently than code spans, if you want to differentiate them.

**Comment by WesCossick** [comment]
I thought that was the case at first too, but it also matches a fenced code block with four back ticks at the top and bottom. Four tick marks would mean two pairs of inline, single line code spans.

**Comment by brondsem** [comment]
I don't remember exactly how code spans are parsed by the markdown mode, but the CommonMark spec says they can be multiple ticks, so four consecutive would begin one span.  See the first sentences of http://spec.commonmark.org/0.22/#code-spans

**Comment by WesCossick** [comment]
Interesting, I did not know that. I'm guessing, then, there isn't a great way to disable fenced code blocks.

**Comment by marijnh** [comment]
I think you'll just have to live with not being able to turn off highlighting for such blocks, yes.
