### ISSUE TITLE
Multiplex + markdown header issue.

### ISSUE THREAD

**Issue by Carreau** [codemirror/CodeMirror#3535]
Hi there,

I have an edge case issue with Markdown & multiplex, I might be doing things wrong.
Basically I have a markdown/latex multiplexed mode, and the following sequence seem to be parsed wrongly by the mode:

```
# Header

$some math$ text that should not be header but appear to be
```

I define my mixed mode as follow:

```js
CodeMirror.multiplexingMode(
    CodeMirror.getMode(config, "gfm"),
    {open: "$", close: "$",
     mode: CodeMirror.getMode(config, "stext"),
     delimStyle: "delimit"}
  )
```

and I made a minimal reproductible example here: https://github.com/Carreau/CodeMirror/commit/252ba1818b698d100f89254fbe3ced923ec70dad

And here is a screenshot if it can be clearer. 
![screen shot 2015-09-17 at 11 11 55](https://cloud.githubusercontent.com/assets/335567/9942008/a26537b8-5d2d-11e5-91a9-3b5a3c6bb1fa.png)

I'm not sure if it is bug/feature/unattended side effect/me missuderstandding mixed mode

Thanks !

**Comment by marijnh** [comment]
The markdown doesn't see the start of the line, because that part of the stream is multiplexed to the stex mode. I've pushed a patch that makes the markdown mode more robust in this case, but in general, multiplexing has its dangers -- it'll hide part of the stream from the multiplexed modes, which some modes don't handle well.

**Comment by Carreau** [comment]
Thank you very much !
