### ISSUE TITLE
roboto mono face, bold, and matching paren moves cursor

### ISSUE THREAD

**Issue by scottdraves** [codemirror/CodeMirror#3603]
to reproduce: 
1) open the following jsfiddle: http://jsfiddle.net/1c0f6aqL/1/
2) Click anywhere in the codemirror in the lower-right
3) type '()'
4) the cursor jumps left, in between the parens, instead of remaining to the right.

**Comment by scottdraves** [comment]
note: the bold is involved, if you just stick with just the regular weight, it's fine.
this is where we first encountered this bug: 
https://github.com/twosigma/beaker-notebook/pull/2366
but then it seemed ubuntu mono had problems too:
https://github.com/twosigma/beaker-notebook/pull/2376
and eventually we figured out we could lose just the bold and that would fix it.

**Comment by marijnh** [comment]
This appears to be due to the browser not loading/initializing the bold version of the font until it absolutely has to, and then doing so asynchronous, so that when CodeMirror measures the size of the parentheses, it is getting measurements for some stand-in font, which it uses to calculate the cursor position. And then,  a few moments later, the browser drops in the actual font (apparently before it even draws) which has different dimensions.

A workaround would be to include a bit of hidden bold roboto mono text somewhere in the page, to force the font to be initialized before CodeMirror tries to use it. I'm afraid that's all I can suggest -- I am not aware of any events that, if I don't know in advance what font is going to be used, will tell me that the font of an element was loaded.

**Comment by scottdraves** [comment]
thank you for researching and explaining that, we were quite baffled.

**Comment by samccone** [comment]
cc @paulirish -- could this be related to the issue around the browser not fetching the font until a recalc is tripped?

I wonder if a force recalc and an explicit wait for the font to be downloaded until the cursor position is calculated in codemirror could be a fix...
