### ISSUE TITLE
Can't add a listener for "onPaste" event

### ISSUE THREAD

**Issue by KeViNOne** [codemirror/CodeMirror#3675]
I have tried many way to add a listener for onPaste event, but failed finally.

```javascript
cm.on('paste', function (event) { console.log('onPaste!'); return true; });
cm.on(cm.display.input, 'paste', function (event) { console.log('onPaste!'); return true; });
cm.on(cm.display.input.textarea, 'paste', function (event) { console.log('onPaste!'); return true; });
```

None of these can work...
Guys, help me...

**Comment by marijnh** [comment]
`cm.getInputField().addEventListener("paste", function() {...})` or equivalent should work, but that will only fire after CodeMirror's own paste handling has happened. There is currently no way to override the built-in paste handling, because that is composed of several hacks and exposing an interface to override them all in a consistent way would be tricky.
