### ISSUE TITLE
Vim bindings: motion commands (jkhl) perform action once, even when held

### ISSUE THREAD

**Issue by scottsievert** [codemirror/CodeMirror#3678]
When using the vim bindings, when I press and hold a motion key (jkhl) I only move one line. This is not as expected -- default vim goes multiple lines after some delay when held. I can get around this issue by eyeballing 20 lines and pressing `20j`, but that's not optimal.

Further information:

* tested with [online vim bindings demo] in all browsers below
* tested on Safari 9.0, Chrome 46.0.2490.86, Firefox 42. Issue present in all cases
* operation system: OS X 10.10.5
* I found this issue while using vim bindings in the Jupyter notebook https://github.com/lambdalisue/jupyter-vim-binding/issues/17

[online vim bindings demo]:http://codemirror.net/demo/vim.html

**Comment by marijnh** [comment]
I can't reproduce this on Linux. Will try on OS X later.

**Comment by marijnh** [comment]
It does indeed happen on OS X where, contrary to other platforms, if you `preventDefault` a `keypress` event, no repeat events are fired for that key as it is being held down. We do need to call `preventDefault`, since we don't want pressing J to type a `j` character.

@mightguava Would it be problematic to have `cmKeyToVimKey` convert events like `J` (keydown) to `j` and `Shift-J` to `J` to work around this issue?

**Comment by cldwalker** [comment]
A couple of LightTable users have experienced this issue as well - https://github.com/LightTable/Vim/issues/49 . This is caused by an os-level global config that changed in 10.9 or 10.10. You can globally disable that config in shell with `defaults write -g ApplePressAndHoldEnabled -bool false`

**Comment by scottsievert** [comment]
Hm, no luck here. Is a restart is required?

**Comment by scottsievert** [comment]
Confirm, restart fixed it.
