### ISSUE TITLE
Atomic marker ruins selection

### ISSUE THREAD

**Issue by MarcelGerber** [codemirror/CodeMirror#3699]
1. Go to http://codemirror.net/
2. Open a console and type:
``` js
editor.markText({line: 6, ch: 0}, {line: 7, ch: 0}, {atomic: true, inclusiveLeft: true, inclusiveRight: true});
editor.setSelection({line: 5, ch: 0}, {line: 6, ch: 0});
```

Result:
Selection spans from line 6 to 8.

Expected:
Selection spans over line 6.

This is a regression in 1fae53703cf4099d4f4855ef18dd14d60514c82f.

**Comment by marijnh** [comment]
Why do you consider the old behavior more correct? We can't have a selection ending at 6:0 if there's a range with inclusiveLeft enabled starting there, so that end of the selection has to be moved somewhere. The old algorithm, mostly by accident, pushed it back to 5:21, the new algorithm pushes it forward to 7:1. Both seem acceptable.
