### ISSUE TITLE
cursorActivity fires on setSelection(-s), origin unclear

### ISSUE THREAD

**Issue by den1k** [codemirror/CodeMirror#3723]
Is there a way to find out whether a selection or cursor move was triggered by the user vs. set programmatically?

a) I don't see an `.origin` on the `.ranges` object in `"beforeSelectionChange"` which would help ignore the event
b) Similarly there is no indication of `.origin` in `"cursorActivity"`

**Comment by marijnh** [comment]
It fires on every selection change, by design. And `cursorActivity` is batched by operation, and thus not associated with a specific selection change, so it couldn't pass an origin.

Attached patch passes `beforeSelectionChange` events an `origin` field. I'm not sure how useful this will be, since origins aren't always passed to selection changes, but it might help.

**Comment by den1k** [comment]
Thank you @marijnh !!
