### ISSUE TITLE
Horizontal scroll bar obstructs last line of text after Paste in FireFox

### ISSUE THREAD

**Issue by SusanDoan** [codemirror/CodeMirror#3821]
Steps to Repro:
1. Use FireFox (Chrome does not repro)
2. Go to https://codemirror.net/demo/fullscreen.html
3. Delete all text in the editor
4. Enter a bunch of text so the vertical scroll bar appears, but NOT the horizontal scroll bar, and also make sure there is no new line at the bottom of the editor.
5. PASTE text (to any line but the last) to cause the horzontal scroll bar to appear

=> scroll to the bottom left of the editor and notice the horizontal scrollbar is partially obstructing the last line of text

![codemirrorhorizscrollpaste](https://cloud.githubusercontent.com/assets/17186762/12993656/50e13e98-d0d0-11e5-9e42-64efaf946040.PNG)

**Comment by marijnh** [comment]
I am not able to reproduce this. Here's concretely how I'm following your instructions:

* Open the fullscreen demo.
* Select all content of the editor, press ctrl-x to cut
* Spam letter keys until there line is long enough to cause a horizontal scrollbar
* Move to the middle of the the line (or don't, both cause the same outcome)
* Press ctrl-v to paste

The cursor now moves to the end of the pasted content, near the bottom of the document, and the last line is visible, above the horizontal scrollbar. If I add a few extra lines so that pasting doesn't put the cursor on the last line, the problem still does not show itself.

This is Firefox 44 Linux. Which OS are you testing on?

**Comment by SusanDoan** [comment]
Thanks for getting back to me!

I see this on Firefox 43.0.1, Windows 7 and Firefox 41.0.2, Mac OSX Yosemite.

I think you went wrong on step 4 - you should spam letter keys until the **Vertical** scrollbar appears.

**Comment by marijnh** [comment]
Ah, sorry for the poor reading. Looks like a bug (or at least strangeness) in Firefox's interpretation of a padding I'm setting. Attached patch seems to work around it. Does it help?

**Comment by adrianheine** [comment]
I suppose the patch fixed this. Feel free to re-open if that is not the case.
