### ISSUE TITLE
Can I use my syntax highlighting rule that already exists in compiler?

### ISSUE THREAD

**Issue by zhanzhenzhen** [codemirror/CodeMirror#3825]
I have designed a language of my own. In the compiler I wrote a highlighting function which outputs "styles" in the format like this:

```javascript
[[0, 0, "normal"], [0, 5, "string"], [0, 25, "comment"]]
```

where the numbers are the row and column.

So, my question is: can I convert this to make it directly used by the editor?

**Comment by marijnh** [comment]
Because CodeMirror highlighting works in a streaming way, it is not cleanly compatible with single-shot parsers, but if your documents are small, you can still get this working pretty well by wrapping your data structure in a CodeMirror mode that tracks its current line and column, and fetches tokens from the data structure. Re-call `setOption("mode", ....)` every time the parsed content changes to trigger a new highlighting pass.

This is a question, not an issue. In the future, use the [discussion forum](https://discuss.codemirror.net/) for those.
