### ISSUE TITLE
[javascript mode] Template strings in ES6 files break syntax highlighting

### ISSUE THREAD

**Issue by dpursehouse** [codemirror/CodeMirror#3865]
Go to the [javascript mode page](http://codemirror.net/mode/javascript/index.html) and paste this code:

```
  <a
    href="#"
    data-filter={`${this.props.interface} ${this.props.device}`}
    onClick={this.filterByInterfaceOrDevice}
  >
    {this.props.interface}
  </a>
```

Everything after (and including) the closing backtick and curly brace are highlighted orange.

Originally reported on Gerrit Code Review ([issue 3947](https://code.google.com/p/gerrit/issues/detail?id=3947))

**Comment by marijnh** [comment]
That's not JavaScript. You're probably looking for the [jsx mode](http://codemirror.net/mode/jsx/).

**Comment by dpursehouse** [comment]
Oh, OK.  Thanks.

**Comment by alexanderdickson** [comment]
It fails for any ES6 template string in real JavaScript too. Discovered with Gerrit.

**Comment by marijnh** [comment]
No it doesn't. If you're going to spam the issue tracker, at least make the effort to submit a failing case.

**Comment by alexanderdickson** [comment]
Sorry, you're right I should have provided some more info.

It definitely does seem to go funny in a file with extension *js*.

![image](https://cloud.githubusercontent.com/assets/511428/13630857/caf4701c-e5e1-11e5-8d24-1d84154a059b.png)

According to `CodeMirror.version`, it's at 3.20.1. I can see it works [here](http://codemirror.net/mode/javascript/index.html), so I can only assume it's because the Gerrit I am using is using such an older version of CodeMirror.

In that case I will upgrade the Gerrit I am using. Apologies for my laziness.

**Comment by marijnh** [comment]
Try pasting your code into http://codemirror.net/mode/javascript/ . I typed in a rough approximation of it (can't copy-paste images) and that seemed to highlight properly.

**Comment by alexanderdickson** [comment]
I tried that and it worked fine, so I put it down to the version of Gerrit I am using is using a much older version of CodeMirror.
