### ISSUE TITLE
Automatic trailing whitespace removal etc. can't preserve redo stack

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#3880]
Say you have a system which removes trailing whitespace on a timer. Then this can happen:
1. Start at a state with some trailing whitespace
2. Perform some edits
3. Undo all the edits from 2
4. Automatic trailing whitespace removal happens

Expected:
The 'redo' command still lets you recreate the editor states up to the state after 2.

Actual:
There's no `origin` string (that I could find) which allows the expected behavior to happen. The trailing whitespace removal necessarily clears the redo events.

It's very possible I'm missing some special `origin` string, or another way to do this.

**Comment by marijnh** [comment]
CodeMirror's history is linear -- i.e. it just implements rolling back and forward to the precise state you had before. Thus, making a change clears the redo history, and there's nothing I can do about that short of rewriting the history (& a bunch of other aspects of the system, because this would involve being able to 'rebase' changes relative to each other and such).

(This may happen at some point in the far future, but for now, the behavior you want is simply not supported.)
