### ISSUE TITLE
PostgreSQL JSON hashbang trigger comment in sql mode.

### ISSUE THREAD

**Issue by coryasilva** [codemirror/CodeMirror#3888]
The [json query syntax](http://www.postgresql.org/docs/9.5/static/functions-json.html) uses a `#` character to some of its queries involving json.  I have provided a [demonstration of the issue here](https://plnkr.co/edit/XcQpXGgVHi8JEA1dq5sp?p=preview)

Would this be difficult to resolve?

**Comment by marijnh** [comment]
Since this appears to be a whole new language (and not a very complicated one), you're probably best off writing a new mode for it.

**Comment by whitelynx** [comment]
This isn't a new language, though... it's part of PostgreSQL's dialect of SQL. (which is [theoretically supported by the existing SQL mode](https://github.com/codemirror/CodeMirror/blob/master/mode/sql/sql.js#L361))

I think the issue is that the `#` character should _not_ start a comment in this SQL dialect; see <https://www.postgresql.org/docs/9.5/static/sql-syntax-lexical.html#SQL-SYNTAX-COMMENTS>. (probably not in _most_ SQL dialects, though I'd have to go digging through their docs to verify that)

Could this be reopened, since it is a bug in a currently-supported dialect?

**Comment by marijnh** [comment]
I'd review a pull request that adds support for this (it's probably not too hard to build on top of the existing `hooks` feature of the SQL mode), but I'm not actively working to fully support for all corner cases of all SQL dialects in my own time.
