### ISSUE TITLE
toggleComment in a multi-line python string keeps adding # characters 

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#3941]
Repro:
1. have a CodeMirror with the following content
```python
"""
test
"""
```
2. repeatedly toggle comment on the test line (or e.g. sublime's toggleCommentIndented)

Expected:
The line gets commented and uncommented, or just stays as a string.

Actual:
Each 'toggle' adds another '# ' at the start of the line.

**Comment by marijnh** [comment]
The issue is that there's not language-independent way to determine whether inserting a comment string at a given position is actually going to create a comment. One option would be to insert the characters and then verify whether a comment was created, but that's a bit of a kludge, and pollutes the editor's history with nonsense changes.

**Comment by mtaran-google** [comment]
How about adding another class like multiline-string (for the languages that support such a thing) and including that in the commenting heuristics?

**Comment by marijnh** [comment]
Attached patch uses a rather sloppy (but probably effective in most languages) heuristic to distinguish multi-line strings from strings that start at the start of the line. Does it help in your case?

**Comment by mtaran-google** [comment]
That works well for our use cases, thank you :)
