### ISSUE TITLE
[vim] Esc not working properly in Safari

### ISSUE THREAD

**Issue by ElDeveloper** [codemirror/CodeMirror#3993]
I'm trying out this example:
https://codemirror.net/demo/vim.html

Whenever I press `<Esc>`, the cursor is gone and I have to click in the text area to get the cursor back.

I'm using Safari Version 9.1 (11601.5.17.1) in OS X 10.11.4 (15E65).

**Comment by marijnh** [comment]
I can't reproduce this on Safari 6, which is the latest version that will install on my test Mac. (And since Apple ties Safari versions to OS X versions, and OS X versions to hardware, I really don't have the budget to say up to date.)

Can anyone who's paid the Apple hardware tax recently test to see whether not being able to override the behavior of Esc is something that Safari 9.1 does?

**Comment by slonoed** [comment]
Safari 9.1.1 (11601.6.17) OSX 10.11.5 (15F34)
Esc and Ctrl+c work fine

**Comment by ElDeveloper** [comment]
My apologies, I just realized this was being caused by a third party plugin, thanks @marijnh & @slonoed.
