### ISSUE TITLE
rulers + lineWrapping = unnecessary scrollbar

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4042]
#### Repro:

1. Enable a ruler at some column position (say 80)
2. Enable line wrapping
3. Type in a long line of text (say longer than the ruler)
4. Make the editor narrower than the ruler position

#### Expected:

Ruler goes off the side of the editor (becoming unreachable), the text is wrapped to be fully visible in the viewport, and no scrollbar appears.

####  Actual:

A scrollbar appears, but the text is still wrapped to the width of the viewport. If you scroll right, you see a gap with no text in it.

I got it to happen in demo/rulers.html with the following content:

```html
<!doctype html>

<title>CodeMirror: Ruler Demo</title>
<meta charset="utf-8"/>
<link rel=stylesheet href="../doc/docs.css">

<link rel="stylesheet" href="../lib/codemirror.css">
<script src="../lib/codemirror.js"></script>
<script src="../addon/display/rulers.js"></script>
<style type="text/css">
  .CodeMirror {border-top: 1px solid #888; border-bottom: 1px solid #888;}
</style>
<div id=nav>
  <a href="http://codemirror.net"><h1>CodeMirror</h1><img id=logo src="../doc/logo.png"></a>

  <ul>
    <li><a href="../index.html">Home</a>
    <li><a href="../doc/manual.html">Manual</a>
    <li><a href="https://github.com/codemirror/codemirror">Code</a>
  </ul>
  <ul>
    <li><a class=active href="#">Ruler demo</a>
  </ul>
</div>

<article>
<h2>Ruler Demo</h2>

<script type="text/javascript">
  var nums = "sasssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss", space = "          ";
  var colors = ["#fcc", "#f5f577", "#cfc", "#aff", "#ccf", "#fcf"];
  var rulers = [], value = "";
  for (var i = 1; i <= 1; i++) {
    rulers.push({color: colors[i], column: i * 80, lineStyle: "dashed"});
    for (var j = 1; j < i; j++) value += space;
    value += nums + "\n";
  }
  var editor = CodeMirror(document.body.lastChild, {
    rulers: rulers,
    value: value + value + value,
    lineWrapping: true,
    lineNumbers: true
});
</script>

<p>Demonstration of
the <a href="../doc/manual.html#addon_rulers">rulers</a> addon, which
displays vertical lines at given column offsets.</p>

</article>
```

**Comment by marijnh** [comment]
I think attached patch will help.

**Comment by axil** [comment]
Hi @marijnh,

After applying this patch the ruler got shifted and now it strikes a letter instead of separating the letters:
![image](https://user-images.githubusercontent.com/170910/30775909-18231586-a0c7-11e7-8392-999f3c490871.png)
Before the patch it was like that:
![image](https://user-images.githubusercontent.com/170910/30775918-418fea84-a0c7-11e7-82a7-fdc9e11bf6e3.png)
I looked into the html and saw that before the patch the `.CodeMirror-rulers` div was inserted inside the `<div style="position: relative; top: 0px;">` tag while now it is inserted right before it. That's why now the ruler is shown 0.4em to the left of the expected position (0.4em is the padding of the `.CodeMirror-lines` div).

I've checked with two different setups on Chrome 61.0.3163.100 (Official Build) (64-bit) (latest as of today), on Windows 7 x64.

Do you observe the same symptoms? Is it possible to get the ruler back where it was before the patch?

**Comment by axil** [comment]
Here's a patch that reverts the shift. Not sure if it still fixes the original issue of the unnecessary scrollbar though.

**Comment by marijnh** [comment]
I'm not seeing the shift in http://codemirror.net/demo/rulers.html. What triggers it?

**Comment by axil** [comment]
This is notebook==4.2.3:
![image](https://user-images.githubusercontent.com/170910/30784711-b9c92cbe-a184-11e7-9047-a0c1de52cfec.png)
Here `div.CodeMirror-ruler` is inside `'<div style="position:relative; outline:none">'` so its position is counted relative to the inside of `.CodeMirror-lines` i.e. 0.4em from its start.
Now this is notebook==5.1.0:
![image](https://user-images.githubusercontent.com/170910/30784744-393b4ad6-a185-11e7-811d-1e45ad2b26ef.png)
Here `div.CoreMirror-ruler` is outside of the  `'<div style="position:relative; outline:none">'` so its position is counter relative to the start of the `div.CodeMirror-lines` without taking its padding into account which results in being 0.4em to the left of the proper position.

**Comment by axil** [comment]
Concerning the demo page.

The layout structure of the http://codemirror.net/demo/rulers.html is slightly different from jupyter-notebook.
Namely, element responsible for this padding 
![image](https://user-images.githubusercontent.com/170910/30854006-974b421a-a2da-11e7-8f98-85ada22e4efe.png)
is different.

In jupyter it is 

![image](https://user-images.githubusercontent.com/170910/30854058-be35bf18-a2da-11e7-9c49-90fb4f1b74b3.png)

and in your demo it is 

![image](https://user-images.githubusercontent.com/170910/30854086-db1e7944-a2da-11e7-866c-0cfc5f1eb536.png)

That's why the shift is not visible in the demo page.

**Comment by marijnh** [comment]
> The layout structure of the http://codemirror.net/demo/rulers.html is slightly different from jupyter-notebook.

Right, that's why codemirror.css has these comments:

```css
.CodeMirror-lines {
  padding: 4px 0; /* Vertical padding around content */
}
.CodeMirror pre {
  padding: 0 4px; /* Horizontal padding of content */
}
```

I.e. the fact that horizontal padding should be set in `.CodeMirror pre` is an assumption the library makes (not just in the ruler addon), and which you should stick to.

**Comment by axil** [comment]
Emm, by 'you' you mean me as a jupyter developer or me as an end user? I'm afraid I'm the second, not the first :) I was sort of reporting an issue that broke the 'ruler' plugin from working in jupyter-notebook. And I've traced back the problem to the fix of this ticket. What's your suggestion on whom should I address with bugreport?

**Comment by marijnh** [comment]
I guess filing an issue with Jupyter is appropriate then.
