### ISSUE TITLE
addon closetag: dontCloseTags seems ignored when whenClosing is true

### ISSUE THREAD

**Issue by ficristo** [codemirror/CodeMirror#4165]
As the title say. 
```json
{
  "closeTags": {
    "dontCloseTags": ["div"],
    "whenOpening": false,
    "whenClosing": true  
  }
}
```

**Comment by marijnh** [comment]
Tag closing uses the XML mode's state to determine which tag is currently open. You'll have to configure your XML or HTML mode to include the tags that are self-closing in its 'autoSelfClosers` option.

**Comment by ficristo** [comment]
I cannot find the documentation for `autoSelfClosers` but doesn't seems what I want.
For example If I have `"dontCloseTags": ["cfset"]` and `"whenOpening": true` when I write `<cfset>` will  correctly not be closed: I'll end up with `<cfset>` without closing tag.
But if I have `"whenOpening": false, "whenClosing": true` the tag will be closed: `<cfset></cfset>`.
I was expecting to have `<cfset>` only.

**Comment by marijnh** [comment]
What kind of language are you editing, and which mode are you using for that?

**Comment by ficristo** [comment]
I'm cross filing from https://github.com/adobe/brackets/issues/12670. /cc @jGeek314.
I think it is ColdFusion Markup Language (CFML) and I suppose the mode is html.

Could you clarify the purpose of `dontCloseTags` attribute and it's relation with `autoSelfClosers`?
Maybe I misunderstood it's purpose.

**Comment by marijnh** [comment]
In normal XML, all tags must be closed. In HTML, there's a list of exceptions that `dontCloseTags` defaults to when the mode is HTML. I don't think this issue has come up before because when people extend XML, they are usually clever enough to not introduce additional strangeness. I guess ColdFusion is an exception.

You'll get ugly highlighting in the XML/HTML mode (false-positive unclosed tag errors) already if you don't tell it that this tag doesn't need to be closed. So you should do something like `{name: "xml", autoSelfClosers: {"cfset": true}}`, except that, if this is embedded in HTML, you should also include the whole default HTML list (from near the top of `mode/xml/xml.js`) in the `autoSelfClosers` object.

**Comment by ficristo** [comment]
@marijnh thank you.

**Comment by jGeek314** [comment]
@marijnh could you point me in the direction of where you put the code: mode: {name: "xml", autoSelfClosers: {"cfset": true}} to make this work in brackets? I can't seem to find any documentation on it anywhere.

**Comment by marijnh** [comment]
I don't know anything about brackets. That was an option to CodeMirror to specify the mode.
