### ISSUE TITLE
Compression helper failing (502 Bad Gateway)

### ISSUE THREAD

**Issue by rcgoncalves** [codemirror/CodeMirror#4187]
I tried to use the compression helper a few times over the last days, but it is always failing with a 502 error (Bad Gateway).

**Comment by marijnh** [comment]
Seems to be working. Are you doing anything special when using it?

**Comment by rcgoncalves** [comment]
I just selected the library, a dozen of modes, and three add-ons.  The page would take about 60s processing, after which it would return a "502 Bad Gateway" error.

I just tried it again, and it now returns a "504 Gateway Time-out" instead.  Considering the 60s it was taking to process before, I guess it was also a timeout problem.

**Comment by marijnh** [comment]
Indeed, when you select a lot of files the thing seems to get much slower and hits nginx's timeout. The compression helper is going to go away soon (almost everyone is using some kind of build step in their project anyway, and I don't feel like keeping the service running), but in the meantime, I've upped the timeout, so that the error you describe should be harder to hit.

**Comment by meglio** [comment]
So, it seems as if the compression helper now gone. What should we do if we don't have any build steps?

**Comment by adrianheine** [comment]
You can still include all files you need separately, if you don't have any build process.
