### ISSUE TITLE
explicit (but same) lineSeparator in separate editors causes extra \r on copy/paste

### ISSUE THREAD

**Issue by leeoniya** [codemirror/CodeMirror#4289]
This may be Windows-specific (or any platform that uses `\r`) but...

If there are 2 editor instances, and both have an identical, explicitly-set `lineSeparator: "\n"`, copy-pasting from one to the other causes each line to have an extraneous `\r` char at the end of every pasted line. These should probably be stripped pre-paste to match the target editor's eol.

I tried to mitigate the situation for now by using the paste event, but it didn't have any effect. prolly cause it fires after the fact?

```js
cm.on("paste", function(cm, e) {
   e.clipboardData.setData('text/plain', e.clipboardData.getData('text/plain').replace(/\r/gm, ''));
});
```

I'd prefer not to have to modify the contents post-paste or other hackery.

thanks!

**Comment by marijnh** [comment]
Does this also happen if you paste in text from elsewhere (say, copied in your native text editor)?

**Comment by leeoniya** [comment]
yes, but only when the editor's eol is set to `\r\n`

**Comment by marijnh** [comment]
I could reproduce the latter problem (pasting from native content) but not the issue with pasting between CodeMirror instances. Attached patch makes it so that pasted content always has its line endings adjusted to the current editor's convention, which seems the preferable behavior. Does it solve your issue?

**Comment by leeoniya** [comment]
appears to be resolved 👍
