### ISSUE TITLE
Mobile swipe unpredictable

### ISSUE THREAD

**Issue by justbittin** [codemirror/CodeMirror#4346]
Codemirror v5.20.2

When using stock Google keyboard (or any swipe enabled keyboard) swiping a word creates unpredictable results.

Sometimes the word is not inserted, sometimes the cursor jumps to a random location with no text input, or it will add multiple linefeeds before the word swiped.

Switching (forcing) textarea corrects the swipe issue, however, old backspace android issue reappears.

Thank you

**Comment by marijnh** [comment]
I've pushed some patches that seem to improve this. Could you do another test with the current master branch?

**Comment by adrianheine** [comment]
Since there was no further feedback I'm hoping this is actually improved. In any case, this is one of many issues which are difficult to solve with the fundamental approach currently taken by CodeMirror.

However, we are working on a rewrite (CodeMirror 6) that will overhaul input handling and should address this issue, and we are currently raising money for this work: See [the announcement](https://codemirror.net/6/) for more information about the rewrite and a demo.

Note that CodeMirror 6 is by no means stable or usable in production, yet. It is unlikely that we put more work into issues like these for CodeMirror 5, though.
