### ISSUE TITLE
[javascript mode] exploding curly brackets indentation

### ISSUE THREAD

**Issue by riklomas** [codemirror/CodeMirror#4386]
There seems to be inconsistencies with how curly bracket are exploded in Javascript mode. When writing if, while and for statements, the second curly bracket gets indented differently for all on the top level and when in child functions, there's more inconsistencies with how the second bracket is indented.

I tried the following in [the addon/closebrackets.js demo](https://codemirror.net/demo/closebrackets.html)

```
if () {
    
  }
  
while () {
       
       }
       
for () {
  
}
     
function () {
  
  if () {
      
      }
  
  while () {
    
  }
  
  for () {
    
  }
}
```

**Comment by marijnh** [comment]
When using actual valid code (i.e. with expressions in the `if` and `while` conditions, and a valid `for` form) you'll see much better results.

**Comment by riklomas** [comment]
Sure, I just wanted to flag this up as an issue when the round brackets are empty and that it can be inconsistent with valid conditions. Just something I noticed when my students are using Javascript and getting weirdly indented code. 👍

**Comment by enkuso** [comment]
Found this closed issue while I was creating new issue. Is there a quick fix/solution for this issue?

*Below is a bug report I was about to create.*

----

Wrong indention happens on JavaScript mode with closebrackets enabled when I type `if` or `while` statement and type no expression inside parenthesis and type brackets and hit enter. Closing bracket have extra indention.

I believe this issue is also produceable without closebrackets.

Other languages do not have this issue and works as expected. 

**Issue** 
This issue is only applicable to the `if` and `while` statement on JavaScript mode.
Current behavior:
```
  // without expression
  if () {
      |
      }

  // with expression
  if (foo) {
    |
  }
```
Expected behavior:
```
  if () {
    |
  }
```
*`|` refers to cursor*

I used CodeMirror version 5.51.0, the issue is produceable on the [closebrackets demo](https://codemirror.net/demo/closebrackets.html)
