### ISSUE TITLE
Right click cut or copy not possible in Edge browser

### ISSUE THREAD

**Issue by MattQlik** [codemirror/CodeMirror#4408]
When selecting text in the Edge browser a right click brings up the context menu with only two options, Select all and Paste. If you first move a block of text to a new line you can get the full context menu including Ask Cortana, Cut and Copy.
![code mirror edge right click error](https://cloud.githubusercontent.com/assets/15639776/20680989/84a61dbe-b56f-11e6-8eae-952c24881c19.gif)

**Comment by fbuchinger** [comment]
Thanks for reporting this @MattQlik! Since your description doesn't mention the root cause of the issue (text selection gets cleared on right click), I decided to add this more formal description of the bug:

### How to reproduce:
1. Open codemirror.net on IE Edge
2. In the "This is CodeMirror" Demo, try to select some text (either by pressing Ctrl + A or by using the mouse)
3. Right click on the selection

### Expected behaviour:
Selection is kept and browser context menu for text selections is shown (including copy/past/cut options)

### Actual behaviour:
Selection is cleared, general browser context menu is shown (no copy/past/cut options)

**Comment by marijnh** [comment]
It seems the wrong browser specific workarounds were being enabled and/or not enabled because Edge's userAgent string is, well, apparently specifically crafted to confuse people, even more so than traditional userAgent strings. Attached patch works around this, and seems to fix the problems with the context menu.
