### ISSUE TITLE
GraphQL mode

### ISSUE THREAD

**Issue by schickling** [codemirror/CodeMirror#4455]
I'm aware of [graphql/codemirror-graphql](https://github.com/graphql/codemirror-graphql) nonetheless I think it would make sense to support syntax highlighting for GraphQL out-of-the-box without the need for another package.

**Comment by marijnh** [comment]
We're planning to move to having _less_ languages in the main distribution, in order to reduce maintenance burden. So no, moving external packages in isn't an option.

**Comment by schickling** [comment]
I see. Will there be some kind of `contrib` Github organization and a standartized way around using languages?

**Comment by marijnh** [comment]
Yes, but I've been too busy with other stuff to set something up.

**Comment by acao** [comment]
@marijnh is it possible we could re-open this? I'm one of the maintainers for codemirror-graphql as of recent. would be nice to ship with support for just syntax highlighting. If it matters, monaco ships with a simple default graphql mode out of the box now. The way we have architected it, the mode is already a standalone module within our package. `codemirror-graphql` contains a bunch of other code that would be irrelevant. So let me know if you'd still be open to a slim PR?

**Comment by marijnh** [comment]
No, we're not going to add modes anymore. You'll have to distribute it as a separate package.

**Comment by acao** [comment]
we already do, with hundreds of thousands of downloads a week on npm, its called codemirror-graphql

all im asking for is a simple syntax mode. the reason is that my employer, a f50 company, is still on bitbucket server which only has your default modes as of bb 3.5. i think i understand why GraphQL cant take precedence over F***script though its used far more, guessing for legacy reasons? will codemirror 6 reset which modes are shipped in their core? monaco has a nice list of no more than 22 that theyve researched carefully if you were curious. they implement syntax support in about 60 lines. our existing syntax mode is only a few lines but thats because we bring in our streaming parser

**Comment by marijnh** [comment]
> will codemirror 6 reset which modes are shipped in your core?

Yes. It'll ship 0 modes in the core.
