### ISSUE TITLE
CTRL+F not working

### ISSUE THREAD

**Issue by philipacrowe** [codemirror/CodeMirror#4491]
If i try and search for a phrase that exists file i have loaded in code mirror i can only find the phrases visible to the portion of code i can see in the browser window. the browser search only finds the other instances if i scroll further down so that the phrases and show in the visible portion of the editor.

**Comment by schanzer** [comment]
Set `viewportMargin` to Infinity.

**Comment by philipacrowe** [comment]
This causes the page to go into an infinite loop. Ive set it to 10000 and it does let the search work but there's a noticeable difference in page load speed.

**Comment by schanzer** [comment]
You want to have your cake and eat it too. If you're using the browser's native search functionality, you are limited to searching only what is rendered. If you want to search EVERYTHING, you need to render everything, and pay the speed cost.

If you want to avoid this, you need to give up on using the browser's native search. Check out the [search addon](https://codemirror.net/doc/manual.html#addons)

**Comment by marijnh** [comment]
Yes, @schanzer explained it well. If you can reliably reproduce `viewportMargin: Infinity` causing an infinite loop, please submit another issue with an example (I couldn't get the problem to occur).

**Comment by gaearon** [comment]
It probably doesn’t help to pile on here, but here is an example of how this issue (if I understand correctly) affects GitHub editor usability.

This is browser search works. I press Enter and jump to the next result:

![](https://d3uepj124s5rcx.cloudfront.net/items/0L3b3B092q2a1U2o382P/Screen%20Recording%202017-03-05%20at%2003.14%20PM.gif?v=3b93752f)

This is how CodeMirror search works inside GitHub UI. I press Enter, don’t see the match, press Enter again, and now screw up the code:

![](https://d3uepj124s5rcx.cloudfront.net/items/033p0v0I2E3E1W3T3108/Screen%20Recording%202017-03-05%20at%2003.15%20PM.gif?v=8427e1b4)

The problem is that when CodeMirror scrolls to the next match, it doesn’t take the editor position in the viewport into account. So the highlighted match is actually below the cut, and I don’t see it.

I also use Enter for skipping to the next result, but CodeMirror moves my selection to the match on Enter. So pressing Enter deletes the match. And since it’s out of viewport, I don’t even see the broken code until I further scroll down.

Sorry if this isn’t helpful, or if I’m barking up the wrong tree. Cheers!

**Comment by marijnh** [comment]
> The problem is that when CodeMirror scrolls to the next match, it doesn’t take the editor position in the viewport into account. So the highlighted match is actually below the cut, and I don’t see it.

Can you reproduce that in http://codemirror.net/demo/search.html ?

> I also use Enter for skipping to the next result, but CodeMirror moves my selection to the match on Enter.

The CodeMirror search UI is not the browser's search UI. But the good news is that it's a separate addon that you can replace with your own implementation, using whichever approach you prefer.

**Comment by gaearon** [comment]
>Can you reproduce that in http://codemirror.net/demo/search.html ?

Yes, if I make the window small enough so that CodeMirror div doesn't fully fit in the viewport. From CodeMirror's own point of view, it scrolls to where it needs to, but it doesn't compensate for the fact that only part of CodeMirror div is visible. 

![](https://d3uepj124s5rcx.cloudfront.net/items/2A032o2v3d1g2o1Q1M1b/Screen%20Recording%202017-03-08%20at%2011.04%20AM.gif?v=7794e15f)

>The CodeMirror search UI is not the browser's search UI. 

I understand this. Is there any reason why keyboard shortcuts don’t follow browser behavior though? I can consistently navigate search results with Enter in Chrome, Firefox, and Safari. I understand these are not the same, but since it overrides a browser shortcut, it would make sense to me for it to behave consistently with another shortcut the browser supports.

**Comment by marijnh** [comment]
Attached patch should address the scrolling issue.

> Is there any reason why keyboard shortcuts don’t follow browser behavior though? 

Because our search module just works completely differently -- it doesn't keep the search field focused, but puts the focus back into the editor when you search, as is often done in editors. As such, Enter already has a meaning, and can't be used for search-next.

**Comment by gaearon** [comment]
>Attached patch should address the scrolling issue.

Thank you for tackling this!

>it doesn't keep the search field focused, but puts the focus back into the editor when you search, as is often done in editors

Thanks for explaining the rationale. I just tried this in Sublime, Atom, and VS Code, and neither of them switched the focus to the editor on Enter in search:

![Sublime](https://d3uepj124s5rcx.cloudfront.net/items/391l350Q1o160h3j0Q37/Screen%20Recording%202017-03-09%20at%2002.35%20PM.gif?v=acdc92bf)

![Atom](https://d3uepj124s5rcx.cloudfront.net/items/1x0B2Y3r130i2t3a312X/Screen%20Recording%202017-03-09%20at%2002.36%20PM.gif?v=6b7171fa)

![VS Code](https://d3uepj124s5rcx.cloudfront.net/items/010D3A3m0g3L2g171I3L/Screen%20Recording%202017-03-09%20at%2002.39%20PM.gif?v=11b36c46)

I respect that you might be using different editors and we might disagree on this, and won’t press you further. Thank you for your work on CodeMirror!

**Comment by marijnh** [comment]
As added background, maintaining fiddly UI components like the search module isn't my biggest hobby, and this addon is going to be moved out of the main repository into a separate, not so seriously maintained module soon. If someone wants to write a modern, solid alternative and maintain that, that'd be 👌

**Comment by gaearon** [comment]
Fair enough. It’s hard to work both on the core and addons at the same time.

**Comment by kaldari** [comment]
Would it be possible to have CodeMirror render all the content, but only syntax highlight the content in view? That would enable searching, but not negatively affect performance.
