### ISSUE TITLE
Internet Explorer showing weird box

### ISSUE THREAD

**Issue by philipacrowe** [codemirror/CodeMirror#4495]
Hi, 
Using ie 8-11 when I click anywhere on the editor a white selection box appears as seen on the image in the link below. using commands, such as ctrl+c , ctrl + v essentially crashes the browser. I cannot repeat this issue in Firefox, Chrome or Safari. 

https://s30.postimg.org/fmlz0quxd/Screen_Shot_2017_01_16_at_16_38_01.png

Any help would be much appreciated!

**Comment by marijnh** [comment]
Is your editor inside a contenteditable=true element, by any chance?

**Comment by adrianheine** [comment]
Closed until we get further information.

**Comment by RemkoNolten** [comment]
For future reference:

I suspect I got a similar issue, but in my case it was easily fixed by using inputStyle 'textearea' instead of 'contenteditable'. 

<img width="984" alt="screenshot 2019-01-07 at 13 39 39" src="https://user-images.githubusercontent.com/655236/50768721-bf3c6c00-1281-11e9-9781-1724cf813e9d.png">
