### ISSUE TITLE
[markdown mode] Blocks don't interact well with surrounding tags

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4611]
If you render the following in codemirror's md mode:

~~~markdown
<div>

```javascript
 1 < 2
```

</div>
~~~

it highlights the closing div tag as an error, even though it should really be matching the opening div tag above.

**Comment by marijnh** [comment]
The content of an HTML block is parsed, as far as I understand Markdown, _as HTML_, so the `< 2` in there really does look like the start of a tag, and isn't sensible content at that point (the `<` should be escaped). It isn't trivial to notice right away that this is not a tag (tags may span lines), so I also don't think the XML mode should be expected to ignore it. (It could ignore numeric tags, but then, the code could just as well say `1 < x`, or even `var html = "<div>"`, so that doesn't get us much.)

**Comment by mtaran-google** [comment]
The key thing is that an HTML block (per CommonMark at http://spec.commonmark.org/0.27/#html-blocks) can also be terminated by a blank line. So in this case, the point is that the initial `<div>` and the final `</div>` are supposed to be interpreted as *separate* HTML blocks.

**Comment by marijnh** [comment]
Oh, that's a lot easier to handle. Does attached patch solve the problem for you?

**Comment by mtaran-google** [comment]
Seems to work well, thank you :)
