### ISSUE TITLE
updateDisplayIfNeeded stuck in an infinite loop

### ISSUE THREAD

**Issue by flouc001** [codemirror/CodeMirror#4727]
I'm using v5.25.2 in an electron application and I call the `setSize` function passing two integer values. I then get through CMs operation handling code to the `postUpdate` function. In this function the code never escaped the `for (var first = true;; first = false)` loop. When I set a breakpoint in `updateDisplayIfNeeded` I repeatedly observe the `update.force` property to be set to true. Is this something I have somehow triggered? Let me know if you need more information.

**Comment by marijnh** [comment]
I wasn't able to reproduce this. Does adding `update.force = false` at the end of the loop body in `postUpdateDisplay` remove the problem?

**Comment by flouc001** [comment]
Hmm I wonder what could be setting the update to be forced. Yes that's how I have hacked around it for the time being.

**Comment by marijnh** [comment]
Forced updates are used to handle some types of display changes that the regular change-tracking doesn't handle, so they are expected to occur. The update object isn't being recreated, and since nothing is clearing the flag, it seems quite probably that it can prevent that loop from exiting.

Attached patch makes this change.
