### ISSUE TITLE
Got an error when trying to configure editor with scrollbarStyle - "simple" option

### ISSUE THREAD

**Issue by LetItRock** [codemirror/CodeMirror#4728]
Hello, 
I want to customize code editor scrollbars, like it is shown in this demo: [scrollbar demo](https://codemirror.net/demo/simplescrollbars.html)
But I got an error when trying to pass scrollbarStyle option with value "simple":
![przechwytywanie](https://cloud.githubusercontent.com/assets/2607232/25764165/deb61dce-31e6-11e7-99f6-cb4ad5047e84.JPG)

My code looks like:
```javascript
import 'codemirror/addon/scroll/simplescrollbars';
import CodeMirror from 'codemirror'
//... somewhere deeper
const editor = CodeMirror(this.refs.root, {
      scrollbarStyle: 'simple',
      //... other options
    })
```

If I correctly understand that addon script should add configurable through css scrollbar component.
But I see from sources that "initScrollbars" function uses "scrollbarModel" which doesn't have "simple" key and it doesn't have any relation with "CodeMirror.scrollbarModel.simple" which is defined in "simplescrollbars.js", so that probably causes problem here, correct me if I'm not right.

Need some help with that, thanks.

**Comment by marijnh** [comment]
The code looks correct. One thing that sometimes comes up with bundlers or module loaders is that due to resolution shenigans they'll consider the codemirror module you import directly a different module from the one that an addon module imports, and thus it'll register its functionality with a _copy_ of the main module, and the one you get doesn't see it. One way to test this is to add a console.log to codemirror.js and see if it gets shown multiple times. (Though if modes are working, that's probably not the issue.)

**Comment by LetItRock** [comment]
Hello @marijnh, 
Yeah I thought about that and I did console.log inside that "simplescrollbars.js" addon and also inside "codemirror.js", so everything was called correctly. 
"initScrollbars" function is the point when an error happens and here I don't see any relation with what addon does. It simply creates new scrollbarModel, but ignores that addon scrollbarModel.

```javascript
export let scrollbarModel = {"native": NativeScrollbars, "null": NullScrollbars}

export function initScrollbars(cm) {
 //...
  cm.display.scrollbars = new scrollbarModel[cm.options.scrollbarStyle](node => {
   //...
  }, (pos, axis) => {
    //...
  }, cm)
 //...
}
```
Code from "simplescrollbars.js" addon:
```javascript
CodeMirror.scrollbarModel.simple = function(place, scroll) {
    return new SimpleScrollbars("CodeMirror-simplescroll", place, scroll);
  };
```

**Comment by marijnh** [comment]
The crash happens because when the editor starts up, `CodeMirror.scrollbarModel.simple` is undefined, which is set in `simplescrollbars.js`. So there's not a whole lot that _can_ go wrong. Are you sure the console.log in `codemirror.js` only ran once? (I.e. if it ran multiple times, the module -- and thus also the `scrollbarModel` object -- is being duplicated).

**Comment by LetItRock** [comment]
Yes, you was right, it is somehow called twice, one time from "webpack" and second from "node_modules". 
I will investigate what is going on. Thanks a lot for your help.

![przechwytywanie](https://cloud.githubusercontent.com/assets/2607232/25771734/e130f092-3259-11e7-8f56-63342997b6f7.JPG)

**Comment by will-russell** [comment]
@LetItRock Did you find a resolution for this when using in webpack (2.0)?

**Comment by jesusvimlet** [comment]
Same issue for me.
