### ISSUE TITLE
Mark missing token at the end of line

### ISSUE THREAD

**Issue by uiii** [codemirror/CodeMirror#4742]
Hi, I'm creating my custom mode for highlighting a song with chords. The first line of the song consists of song name and song author in parentheses:

```
Take me home, country roads (Denver, John)
```

And I want to mark somehow if the parenthesis at the end is missing. I was trying to create an empty 'error' token but is look it is not possible to create an empty token without advancing the stream. Note I'm consuming the tokens sequentially so when I detect missing parenthesis I cannot back up because song author token is already emitted. What I would like to do is to underline a space (which is not actually present) at the end of line, marking the beginning of the next line as unexpected doesn't make sense in my case.

How can I solve this? Thank you.

**Comment by marijnh** [comment]
This isn't supported. You can do lookahead by calling `stream.eol()` after every token, and styling it as an error if it's not supposed to be the last token on the line, but you can't add tokens where there is no text. Alternatively, emit a [`line-` style](http://codemirror.net/doc/manual.html#token_style_line) instead of adding the error class to the last token, and add a CSS rule that adds a marker to such lines using `:after`.
