### ISSUE TITLE
incorrect cursor position for bold math text

### ISSUE THREAD

**Issue by minrk** [codemirror/CodeMirror#4750]
Bold math text, such as `𝐚` ([MATHEMATICAL BOLD SMALL A (U+1D41A)](http://www.fileformat.info/info/unicode/char/1d41a/index.htm), takes up two characters in cursor calculations, but is only one character.

Can be verified by inputting 𝐚 into any CodeMirror demo and calling `editor.getCursor()`. Appears to be related to #1813, possibly just another codepoint range to be added somewhere.

Reported downstream at https://github.com/JuliaLang/IJulia.jl/issues/541 , https://github.com/jupyter/jupyter_client/issues/259

**Comment by marijnh** [comment]
Is the problem that such a character 'counts' as two characters in string offsets? If so, that's intentional -- JavaScript (unfortunately) represents strings as UTF-16, so 'astral plane' characers like this take up two string indices, and short of writing our own string representation, there's not much JavaScript libraries can do about that.

**Comment by stevengj** [comment]
Yes, `𝐚` is in the astral plane, and it appears that CodeMirror is using 16-byte UTF-16 code units (not Unicode characters) for cursor calculations, since this is how JavaScript indexes strings.  Unrelated to #1813 (combining characters, not surrogate pairs).

Probably Jupyter needs to convert this to/from Unicode character counts (so that it has an encoding-independent index) itself.

**Comment by minrk** [comment]
Thanks, CodeMirror's behavior matching underlying js details makes sense. Adding the workaround in Jupyter: https://github.com/jupyter/notebook/pull/2509

**Comment by oeddyo** [comment]
@minrk this literally saved my life. Thanks!
