### ISSUE TITLE
Shared GutterMarker, LineClasses, LineWidgets

### ISSUE THREAD

**Issue by mrgrimmig** [codemirror/CodeMirror#4788]
Hello,
refering to this issue #2360 i noticed that gutterMarkers, lineClasses and lineWidgets(?) will not be shared in linked documents.
TextMarkers aren't a workaround because i want to share e.g. breakpoints (gutterMarkers).
For now i'm using a custom observer pattern (it has anything to do with CodeMirror) to share this stuff, but maybe anyone else needs the same behavior.

**Comment by marijnh** [comment]
This is going to have to be done in 3rd-party code, as you are doing, because I don't feel that adding that extra complexity and API surface to the core is worth it. I believe it should be possible to write your own `SharedTextMarker`-like class for these various elements that abstracts shared versions of them in a relatively clean way.
