### ISSUE TITLE
Unable to make lint addon work in TypeScript context

### ISSUE THREAD

**Issue by fwielstra** [codemirror/CodeMirror#4796]
I'm working on integrating CodeMirror into my Angular 2 project for a custom scripting language. Getting it running worked fine, getting my own mode registered and working works fine, and implementing the show-hint addon worked fine too.

However, integrating the linter does not work. I've tried all variations (registerHelper, setting a lint object with a getAnnotations field in the config, setting a lint function in the config), but the linter function is simply not called.

I've gone with the old fashioned way and put some HTML script tags into my index.html file, and from there out it works fine.

What's the difference between the show-hint.js and lint.js plugins that makes lint.js not play nice with typescript / es6 imports? My imports look as follows:

```typescript
import * as CodeMirror from 'codemirror';
import 'codemirror/addon/hint/show-hint';
import 'codemirror/addon/lint/lint';
```

**Comment by marijnh** [comment]
Most likely your module bundler ends up duplicating the main library (lib/codemirror.js) because it considers the relative paths to it found in the addons to be different from the plain 'codemirror' you use. This can usually be fixed by configuring your bundler differently, but I'm not familiar with the various bundlers. (To diagnose whether this is happening, you can add a `console.log` to the top level of `lib/codemirror.js` and see if it is run multiple times)

**Comment by fwielstra** [comment]
That makes sense now you mention it; I had the same problem with Angular. In my situation I have an app which depends on a library (my codemirror component) via a symlink. I can fix that. I've removed the codemirror dependency from the 'app'. I really need to figure out how to properly develop an includeable TS / Angular module. Thanks!
