### ISSUE TITLE
Multi-selection ctrl+V behaves unexpectedly depending on CodeMirror internal state

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4800]
0. In some editor, input the string 
```
Foo

``` 
(Foo, trailing newline) and copy this string.
1. open https://codemirror.net/demo/sublime.html
2. double-click `Ctrl` to select it and press ctrl+d to select the next occurrence
3. Ctrl+v to paste

Expected: Foo and newline are inserted at both cursor positions.

Actual: Foo is inserted at the first cursor and nothing is inserted at the second.

If you do the whole procedure within a single codemirror, the expected outcome occurs.

**Comment by marijnh** [comment]
When the number of lines in foreign (non-local) clipboard data matches the number of selections, the editor will paste one line per selection. For local data, the editor knows the exact selections that the data was made out of, so it will treat it as a single selection, even though it contains multiple lines. This is by design.

**Comment by mtaran-google** [comment]
Where is this behavior documented? And what's the motivation for having this context-sensitive functionality, since I don't know of any other editor that behaves this way? 

I do agree that both functionalities have their own use cases, but it would be best to have them as separate commands that each just do the one thing. It's fine to have them not be bound by default – we can do that on our end.

**Comment by marijnh** [comment]
I don't think this behavior is documented anywhere at the moment. If I remember correctly, at some poine someone cared a lot about getting this behavior and I figured it wouldn't hurt.

Unfortunately, there isn't much room for different commands when it comes to pasting -- the browser only allows us to access the clipboard when a native paste even occurs.

Would an option to turn this (spreading N line external content pastes over N selections) off help for you?

**Comment by mtaran-google** [comment]
An option to turn the behavior off would be fine as a workaround, but I do think there is room for the two commands (since as I said, this behavior is quite useful in some cases).

In particular, pasting still happens when you add modifiers on top of ctrl/cmd+v. So if there were different commands for these two behaviors, they should be assigned to ctrl+v, ctrl+shift+v, ctrl+alt+v, etc., and should still work, right?

I'm not suggesting they should be assigned in CodeMirror's keymaps, but we could assign them as such in ours.

**Comment by marijnh** [comment]
Attached patch adds the option (`pasteLinesPerSelection`). Since pasting isn't a command, in the CodeMirror sense, but a regular DOM event, defining different commands doesn't work. You could, however, register a DOM handler for paste that runs before CodeMirror's handling, and sets this new option to the desired value based on the state of a modifier key. Does that work for you?

**Comment by mtaran-google** [comment]
Eh, no that's too much hassle since we also have another system of commands/shortcuts that acts as a superset of CodeMirror's. We'll just set this option to false for now and if someone wants this behavior as a separate command I can point them back at this thread :)
