### ISSUE TITLE
Syntax highlight for org mode

### ISSUE THREAD

**Issue by mickael-kerjean** [codemirror/CodeMirror#4807]
Hello, 

Thank you for maintaining this awesome library. Code mirror is the only one that was working with crappy mobile and it's very appreciated! 

I published a [app](https://github.com/mickael-kerjean/nuage) that make use of codemirror to edit [org](http://orgmode.org/) files. As I couldn't find any mode for org documents, I built one but It might be a better option if its lives in this repo instead.

What do you think?

**Comment by marijnh** [comment]
Hi. Great job on the new mode. I'm not accepting new modules into this distribution anymore, to keep the maintenance work under control, so hosting and distributing it separately is the way to go now. You might want to consider packaging up the mode as an NPM package so that others can easily install it.

**Comment by gfredericks** [comment]
@mickael-kerjean did you ever publish this? I would like to use it.

**Comment by ryanpcmcquen** [comment]
Could one of these libraries help?
https://github.com/daitangio/org-mode-parser
https://github.com/mooz/org-js

**Comment by ryanpcmcquen** [comment]
@gfredericks it is here: https://github.com/mickael-kerjean/nuage
