### ISSUE TITLE
Long appends to long lines freeze the tab

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4822]
1. http://codemirror.net
2. 
```js
let s = 'a';
while (s.length < 4096) {
    s += s;
}
while (editor.getValue().length < 1024*1024) {
    editor.replaceRange(s, {line:0, ch:null}, {line:0, ch:null});
}
```

expected: the tab would freeze only roughly as long as it freezes when you paste in a 1MB line

actual: tab freezes for much longer

We're running into this in a place where we're using CodeMirror in read-only mode (but where the program can append data). If this is happening due to e.g. history being stored, what's the option to pass to disable history? Or is there an origin to pass to the replaceRange command that will make the change not be stored in history?

**Comment by marijnh** [comment]
Is the problem that a bunch of changes together take a long time? If so, have you tried wrapping them in an [`operation`](http://codemirror.net/doc/manual.html#operation)? For me that takes the time from too long to even wait for to 300ms. The issue is that CodeMirror still does redrawing at line granularity, so long lines can get expensive, and by doing the `replaceRange` calls one at a time, you're triggering a redraw of the whole line for every call, which is very quadratic.

**Comment by mtaran-google** [comment]
These chunks are getting streamed in from the network over perhaps several seconds. The chunks in general usually have sane-length lines -- this is just an edge case we encountered. I suppose we could try and do some buffering in our code to build up lines in memory and only do line-wise insertions into the CodeMirror for display. That's probably the sanest approach, would you agree?

**Comment by marijnh** [comment]
Yes, if that's workable, that would probably help.
