### ISSUE TITLE
markText issues with scrolling

### ISSUE THREAD

**Issue by Lee303** [codemirror/CodeMirror#4874]
Hello,

It would appear that markText isn't working as expected when scrolling. An example is available at:

https://p.lee.io/c1056948-1b69-43f5-81ff-260baf2a9bcc#L68

In the above example, line 68 has been marked, however scrolling this line off-screen and back in again causes the rest of the document to become highlighted.

This is using CM version 5.26.0

Any help apprieciated, thankyou!

**Comment by marijnh** [comment]
Can you create a minimal stand-alone demonstration of the issue? I can't debug that page because I have no idea what it's doing.

**Comment by Lee303** [comment]
After stripping this down, I've managed to find the issue - my bad! Apologies for wasting your time.

**Comment by mafar** [comment]
I had same issue,
It happens one has to  use  ```parseInt ()```
```
{
   line: parseInt(lineNumber),
   ch: parseInt(start),
}                
```
without  ```parseInt ()``` , everything works fine , ```markText ``` marks text correctly but when u scroll, most of doc is marked as well

**Comment by icarito** [comment]
Thanks @mafar , this was driving me crazy!
@0x4c6565 I believe you found a legit but.
@marijnh I believe the bug is at `findWordAt` because it returns:

```
anchor: Object { line: "13", ch: 2, sticky: null }
head: Object { line: "13", ch: 8, sticky: null }
```
As you can see, the "line" property is a string, not an Int. Thus, @mafar 's workaround worked, I have gotten rid of spurious marks when scrolling. Thanks!

**Comment by marijnh** [comment]
> I believe the bug is at findWordAt because it returns:

This returns numbers for me. Can you reproduce this with a simple script?

**Comment by icarito** [comment]
Yes this is the simplest I could manage:
https://stackblitz.com/edit/js-kyt191?embed=1&file=index.js

I figured out the issue is when giving text parameters to `markText`. I get these text from parsing the javascript error message, forgot to turn it into an int. Maybe it should work around automatically, or warn about it?

Thanks for CodeMirror!

**Comment by icarito** [comment]
On the shared link, look at line 10, it is highlighted. Then scroll down and see this...

![Captura de pantalla de 2020-04-08 19-05-02](https://user-images.githubusercontent.com/199755/78844647-f8efab80-79cb-11ea-9e92-8a7109f861de.png)

**Comment by marijnh** [comment]
> let row = "10", 
>    col = "4"
> let word = editor.findWordAt(CodeMirror.Pos(row, col))

You're still passing _in_ strings to the method. Just stop doing that, and I'm sure it'll stop giving you back strings.

**Comment by icarito** [comment]
Yes I figured that out. I already fixed that.

But it's a honest mistake with a very bad result (it /seems/to work, 
but then it breaks inexplicably).

So for a better dev experience, it shouldn't accept strings in the 
first place, that is what this bug is about, I guess.

Thanks again.
