### ISSUE TITLE
An idea to solve the backspace problem on mobile

### ISSUE THREAD

**Issue by strongrex2001** [codemirror/CodeMirror#4934]
I'm not familiar enough with Node Js, so I don't know how to modify the source...
Maybe it would help to put an character in the Textarea used for input and ignore it in the code updating the Div, but when it is deleted by the user, raise an "Backspace" Event... I'm not sure.

**Comment by marijnh** [comment]
We're not using the hidden textarea on mobile, because that would prevent the user from selecting text through the touch interface. Instead, we set the content DOM to be editable using `contentEditable`. In many cases, backspace will just do the right thing there, but yeah, not always. This idea won't work, though.

**Comment by strongrex2001** [comment]
emm……Okay……

**Comment by strongrex2001** [comment]
InputConnectionWrapper works strangely on Android 7+ Devices…… I'm using an virtual Backspace Button on the page now……
