### ISSUE TITLE
Closebrackets with custom keys

### ISSUE THREAD

**Issue by blittle** [codemirror/CodeMirror#4953]
I might be missing something, but it doesn't look like the `closebrackets` plugin supports custom characters because it doesn't update the `keyMap` with custom pairs (https://github.com/codemirror/CodeMirror/blob/master/addon/edit/closebrackets.js#L27)

Essentially I'm trying to make codemirror work with a custom language where the comments exist between two `#` characters. I want to add `#` as a closebracket pair for more easily entering text like `# my comment #`

**Comment by marijnh** [comment]
Right, the set of keys to bind is static at the moment, because (due to nested modes) it is not possible for the plugin to see in advance which characters are defined for every mode it will encounter. One solution might be to add a utility function to the addon that allows user code to add new characters to the keymap. Do you want to implement that?

**Comment by blittle** [comment]
@marijnh sure, I'll work out a PR in the next few days.

**Comment by blittle** [comment]
Fixed with https://github.com/codemirror/CodeMirror/commit/e716c17e3bdfd10da477d92bd3fa2fb66cabbaa1
