### ISSUE TITLE
Merge view for identical text shows collapsed line that can't expand

### ISSUE THREAD

**Issue by nchen63** [codemirror/CodeMirror#5054]
Steps to reproduce:
1. Call CodeMirror.MergeView with these options:
```
{
  collapseIdentical: true,
  connect: "align",
  highlightDifferences: true,
  lineNumbers: true,
  mode: "text/html",
  orig: "ab\nab\nab\nab\n",
  origLeft: null,
  value: "ab\nab\nab\nab\n",
}
```
2. inspect HTML

issue: there is a element with `CodeMirror-merge-collapsed-line`, but it can't be expanded. There is no child `CodeMirror-widget`

**Comment by marijnh** [comment]
Attached patch should help. What was happening was that these markers are defined to automatically get cleared when the selection enters them, but since this one spans the whole document, it was immediately cleared because it necessarily covers the selection. That caused two pieces of styling (the collapsing and the class on the top line) to get out of sync.

**Comment by nchen63** [comment]
that was quick! thanks
