### ISSUE TITLE
[core] multi-chord bindings can interfere with single-chord shortcuts

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#5061]
1. https://codemirror.net/demo/sublime.html
2. make an edit
3. press down cmd/ctrl
4. press down and release K
5. press down and release Z

expected:
the edit should be undone

actual:
the edit remains

This doesn't happen if you release the cmd/ctrl issuing the cmd+z, but that's the whole reason why sublime's multi-key shortcuts are that way, so that you don't have to lift your finger off the modifier.

**Comment by mtaran-google** [comment]
actually, it seems this only happens on mac, and not linux, since the the key code there gets interpreted as Mod whereas on linux it gets detected as Ctrl

**Comment by marijnh** [comment]
I'm not 100% sure this is the right thing to do — in Emacs, for example, it works the same way it currently works. If you press a key combination that's registered as a prefix, the next key is interpreted in the context of that prefix, and only in the context of that prefix. The assumption behind that would be that you're intentionally composing keys and that if the thing you type isn't bound, you probably don't want anything to happen.

If, on the other hand, you're fat-fingering some bogus combinations, maybe the first key was an accident and you did want something to happen. Both outcomes are bound to annoy someone, but since multi-stoke keys are rare in CodeMirror, and swallowing keys can confuse inexperienced users, I've implemented the behavior you asked for in attached patch. I didn't test on OS X because I'm not near my Macbook, but I expect the effect should work there as well.
