### ISSUE TITLE
Internal double slashes getting omitted as comments

### ISSUE THREAD

**Issue by mohammadRehaan** [codemirror/CodeMirror#5158]
ex: 
`// some commented line here`
`some genuine line here with slashes: c://dir/someFile.txt`

when you select those two lines at once and use `comment` action via codeMirror api, it removes the comment from first line, which is expected but it also removes the double slashes in second line as well which is not expected.

**Comment by marijnh** [comment]
Which language mode? (In most languages, those slashes on the second line would also start a comment so I'd say the behavior is reasonable.)

**Comment by mohammadRehaan** [comment]
IHi, thanks for quick reply, I really appreciate that.

Actually we have our own language so I think what you said makes sense. I can try fixing our parsers maybe, are you sure that the correct behavior?

**Comment by marijnh** [comment]
Depends on the language.

From what I can see, the comment command will only remove a line comment start if the mode has highlighted it as a comment, so it doesn't look like the issue is there. Going to close this, feel free to add information if you have a concrete issue with something in the distribution.
