### ISSUE TITLE
in mobile, regradless of ios or android，only type one word of one time

### ISSUE THREAD

**Issue by henryatman** [codemirror/CodeMirror#5170]
first of all，CodeMirror is wonderful and powerful editor，but this have a problem really bother me，it‘s  cause editor can't run in phone，

in mobile, regradless of ios or android，only type one word of one time，

no matter how much word  i type，only one word insert to input，it's really problem，

it’s like stipulate only type one word in three second，。。。completely useless in phone，

hope codemirror slove this problem，

btw，i mean type chinese，chinese only type use by input method software

really thanks

**Comment by everywan** [comment]
Change the browser UA to "desktop".
改变手机浏览器的UA为桌面.目前正在查找其他的方法

**Comment by adrianheine** [comment]
I don't really understand the issue here, but we are working on a rewrite (CodeMirror 6) that will overhaul input handling, and we are currently raising money for this work: See [the announcement](https://codemirror.net/6/) for more information about the rewrite and a demo.

Note that CodeMirror 6 is by no means stable or usable in production, yet. It is highly unlikely that we pick up this issue for CodeMirror 5, though.
