### ISSUE TITLE
Where is codemirror.js?

### ISSUE THREAD

**Issue by osworx** [codemirror/CodeMirror#5330]
Maybe I have overseen some, but where is the **codemirror.js**?
You are refering (see demoscripts) to: <script src="../lib/codemirror.js"></script>
Looked inside versions back to 5.2x.x .. nothing?

Therefore also the demos are not working because if missing script!

**Comment by dcooney** [comment]
@osworx You need to cd to the repository and run `npm install`.
After that, `codemirrors.js` will be added to the `lib` directory.

**Comment by osworx** [comment]
Thx, but what if I add the script the 'normal' way, not using any installer?
Such a way to add codemirror to a system should be also possible - thanks in advance.

In the meantime I copied the script manually.

**Comment by dcooney** [comment]
> Such a way to add codemirror to a system should be also possible - thanks in advance.
Yea, I'm not sure why they didn't include the bundled script in the downloaded repository.

**Comment by marijnh** [comment]
> I'm not sure why they didn't include the bundled script in the downloaded repository.

Because it's not part of the sources and doesn't need to be version controlled. Get the package from NPM or the zip on the website if you want a distribution. This here is a source repository.

**Comment by osworx** [comment]
@marijnh That this is a 'source repository' is known!

> get the zip on this website

You're joking, there is no script inside the zip  that's why i am asking.

**Comment by dcooney** [comment]
Nice, thanks for the link @marijnh.
FWIW - I'm still unable to locate the .zip download link on the website.

**Comment by sjlehn** [comment]
I agree with @osworx - the way the releases are set up is confusing. I expect "releases" on Github to include ready-to-run artifacts, alongside the source code. This has been a waste of time the last couple times I've had to update, because I grab the zip from here, try to use it, and find that file missing ("oh right, the zips aren't the same...go find the other one")...perhaps now that I've bothered to complain it'll stick in my head that I can't use the release notification to download the release...

If it's not too much of a headache to implement, it would be really helpful to include a link to the "build" zip, in addition to the source zip, in the Github releases.
