### ISSUE TITLE
possible to use the parent element's scroll?

### ISSUE THREAD

**Issue by jordyvandomselaar** [codemirror/CodeMirror#5342]
Is it possible to scroll the entire page when scrolling through codemirror? I'm creating a live preview on the right of the editor, and I think it would be great if they could both scroll at the same time, by just scrolling the webpage instead of codemirror itself.

**Comment by marijnh** [comment]
It's possible (see [this demo](http://codemirror.net/demo/resize.html)), but it's not very efficient—for huge documents the editor will be slow because it has to keep the whole document in the DOM.

For things that are _questions_, rather than bug reports, please use the [forum](https://discuss.codemirror.net/) rather than the bug tracker.

**Comment by jordyvandomselaar** [comment]
@marijnh Fair point, thanks for the explanation, and for the tip about the forums!
