### ISSUE TITLE
[TypeScript] Arrow functions with a line break in arguments aren't highlight

### ISSUE THREAD

**Issue by alur** [codemirror/CodeMirror#5366]
```typescript
const x = (a: string,
           b: number) => {}
```

**Comment by marijnh** [comment]
Yeah, this is a combination of JavaScript's tricky grammar and the mode's inability to look ahead across line endings. It could be solved for the case where the arrow is on the next line, but not for the general case, and looking ahead a single line is already pretty expensive (it requires more mode states to be invalidated for every change, since they may depend on anything that they looked ahead to). Is this important enough for you to warrant such a change?

**Comment by alur** [comment]
No, it's alright.

I see you added a typescript mode to the google-modes repo now, where this does work :). We will end up switching to that anyways.
