### ISSUE TITLE
Searching for some strings containing backslash finds nothing

### ISSUE THREAD

**Issue by gwarser** [codemirror/CodeMirror#5428]
Tested on http://codemirror.net/demo/search.html
Firefox Nightly, Chromium 66

STR:
- copy this into textbox on demo page 
```
padding
www\tfoo
wwwww	<- tab
www\/?foo
test for t
```
- try searching for `www\t` or `www\/?` using CodeMirror search feature
- nothing is found
- searching for `\n` finds new lines
- searching for `\t` does not find `\t` or tab, but finds `t`

`parseString` in `search.js` replaces `\n` and `\r` to LF and CR, but strips backslashes from other looks-alike escape sequences in query string.

Real case is I cannot find
`/(watchcartoononline|9anime|memecenter|kimcartoon|animeflv).*[a-zA-Z0-9&%=\/?]{40,}/$script,~third-party`

in content of EasyList in uBlock Origin setting

```
...
@@||youtube.com/iframe_api$third-party
@@||youtube.com/player_api$third-party
! 
/(watchcartoononline|9anime|memecenter|kimcartoon|animeflv).*[a-zA-Z0-9&%=\/?]{40,}/$script,~third-party
/(watchcartoononline|9anime|memecenter|kimcartoon|animeflv).*\/.*[(&|=|%|\/|?)]{50,}/$image,script
@@||9anime.is/assets/min/frontend/all.js$script
@@||9anime.is/assets/player/jwplayer-7.12.3/jwplayer.js$script
...
```

Filters may be complicated, and may be not easy to find all backslashes and escape them.

**Comment by gorhill** [comment]
The fix is trivial in practice, which is to slightly rewrite `parseString` in <https://github.com/codemirror/CodeMirror/blob/c9892c85b02e448370798edd374d6cbc9bb41272/addon/search/search.js#L80-L86>:

    function parseString(string) {
        return string.replace(/\\[nrt\\]/g, function(match, ch) {
            if (ch == "n") return "\n"
            if (ch == "r") return "\r"
            if (ch == "t") return "\t"
            if (ch == "\\") return "\\"
            return match
        })
    }

However I am not sure why this was implemented the way it is, so I am unsure whether such change would be accepted.

**Comment by marijnh** [comment]
> However I am not sure why this was implemented the way it is

It is following the way JavaScript/C strings work (with less supported escapes) where unrecognized escapes just result in the escaped character (i.e. `"\i" == "i"`).

There's no well-defined user expectation here — the current behavior was added because people wanted to be able to use `\n`, but disappoints the expectation of being able to insert backslashes the simple way. Your patch would probably cause this to be less surprising, so if you want to submit a pull request that'd be great.
