### ISSUE TITLE
Custom linting doesn't work.

### ISSUE THREAD

**Issue by wIRC** [codemirror/CodeMirror#5441]
I've loaded lint.css and lint.js.

Instantiated an editor:

```
    new CodeMirror(assemblyEditor, 
            {
                lineNumbers: true,
                indentUnit: 4,
                gutters: ["CodeMirror-lint-markers"],
                lint: true
            }
        );
```
And the helper:

        CodeMirror.registerHelper("lint", null, text => {
            console.log("linting:", text);
            return [
                {
                    message: 'Hey!',
                    from: CodeMirror.Pos(0, 0),
                    to: CodeMirror.Pos(0, 1)
                }
            ];
        });

It simply doesn't call the helper function.

**Comment by marijnh** [comment]
I suspect the problem is that you're registering this as a helper without any `name`, so it won't match your editor. Either directly set up your lint function in the `lint` option (with a value like `{getAnnotations: myFunction}`, or put the name of the mode your editor is using as the second argument to `registerHelper`.
