### ISSUE TITLE
CodeMirror$1 in NPM distribution

### ISSUE THREAD

**Issue by tophf** [codemirror/CodeMirror#5507]
NPM distribution has `CodeMirror$1` due to rollup's import-export intricacies, I suppose, but there's no `$1` in the official site version at http://codemirror.net/lib/codemirror.js.

I've been always using the site version, but recently AMO reviewers insisted we switch to the versioned source in NPM so now I see lots of these `$1` for my editor objects in devtools when debugging live code in the browser. It's a visual noise, which I dislike.

![2da57af386](https://user-images.githubusercontent.com/1310400/43044620-276405ae-8db2-11e8-8b4d-a88052f38b73.png)

Can you fix this please?

If it's not possible by re-arranging something in the source files, would you consider a post-build text replacement?

**Comment by tophf** [comment]
FWIW, commenting out `export default CodeMirror` in /src/codemirror.js removes $1 from the rollup output.

**Comment by Mottie** [comment]
Do you want to fork CodeMirror, modify, publish and add it to our update process then?

**Comment by marijnh** [comment]
This my be due to a different version of rollup or one of its plugins being used to build the live version. I don't consider function `name` properties to be a significant part of the exported file, so I don't consider this an important enough issue to investigate. But if you can figure out a way to clean it up (without breaking any backwards compatibility) a pull request would definitely be welcome.
