### ISSUE TITLE
Shared measurement cache / slowdown with computing text height and char width

### ISSUE THREAD

**Issue by tmcw** [codemirror/CodeMirror#5524]
Hi there,

We’re building a site that relies on sometimes many CodeMirror instances - one per code block, which can add up to 30 or 40 in a longer notebook. Profiling long notebooks, like [this one](https://beta.observablehq.com/@mbostock/manipulating-flat-arrays), points to character metrics as a significant performance center: each CodeMirror instance runs charWidth and textHeight when it's initialized, and that adds up to (in my numbers) as much as 10% of the total page initialization JS+DOM time.

Given that all of the CodeMirror instances have the same text metrics, it seems like it'd be ideal to share a cache of these metrics between them, instead of re-calculating per instance. Short of patching our copy, would this be something that could work with the existing CM API? Priority-wise, I'm not sure where it fits because I don't see many other folks running into this issue - possibly just running lots of CodeMirror instances is an edge case?

Thanks,

-Tom

**Comment by marijnh** [comment]
Hi. That's a valid concern, however, there's no guarantee that different editors are styled in the same way (which may depend on parent nodes, themes, classes, etc), so blindly sharing this value doesn't seem like a good idea.

A patch that allows user code to explicitly pass another editor instance to take this cache info from, as an option, would be welcome.

**Comment by futurist** [comment]
I'm also running into this issue, with hundreds of CodeMirror cells in [jupyterlab](https://github.com/jupyterlab/jupyterlab), the top performance bottle is `textHeight`, although all the text height measured is the same.

![image](https://user-images.githubusercontent.com/159167/54728176-49c11600-4bb7-11e9-99d7-205266dc3949.png)

Maybe another way for this issue can pass a **styleHost** to be a container for measure things (like text height, char width...), then keep the measured text element when possible, since `appendChild` then `removeChildren` can trigger a [reflow](https://developers.google.com/speed/docs/insights/browser-reflow)

**Comment by marijnh** [comment]
> the top performance bottle is textHeight, although all the text height measured is the same.

It rather looks like multiple layouts are being forced. Have you tried wrapping all your cell updates in a single call to `.operation` (on an arbitrary editor instance, preferably one that'll be involved in the update) to synchronize the updates?

**Comment by tmcw** [comment]
Thanks for the tip - I think we'll still investigate sharing text metrics, but using startOperation & endOperation looks like a solid win for initial layout time.

**Comment by tmcw** [comment]
Quick update: we did in fact use startOperation & endOperation and got some good performance improvements out of it.
