### ISSUE TITLE
Expand CSS hint functionality

### ISSUE THREAD

**Issue by psmithson** [codemirror/CodeMirror#5571]
Thanks for an awesome plugin. Just made a donation for you, the first of many I think.

I got hinting to work correctly. But I would like to see expanded CSS functionality like this Sublime Text example, in which after a CSS colon, I get a list of relevant options relating to the CSS property I have on the left:

![codemir2](https://user-images.githubusercontent.com/1484015/45250201-daa76280-b2f3-11e8-881d-8805ae6fb16b.jpg)

In CodeMirror, I get a list that is not relevant:

![codemir3](https://user-images.githubusercontent.com/1484015/45250220-48538e80-b2f4-11e8-8a7d-4a4c9a313168.jpg)

Is there a way developed to do this I am not aware of, or could it be added?

Thanks and good luck with the fundraiser.

**Comment by marijnh** [comment]
> Is there a way developed to do this I am not aware of, or could it be added?

The CSS hinter isn't aware of which values are valid with which properties, but it would be able to extend it to do something like that. The only downside is that it'd require a pretty big additional dataset, possibly even with information about the syntax of composite properties (like `border` or `box-shadow`) so that it could hint sensibly inside of those.

I don't have plans to work on this though, and we don't keep feature request issues open unless such plans exist, so I'm closing the issue.
