### ISSUE TITLE
Focused cursor misaligned line

### ISSUE THREAD

**Issue by stoplion** [codemirror/CodeMirror#5724]
Hello.
On first focus of Codemirror, the cursor is position is not right. Whenever I type something it snaps onto a line.
[![Image from Gyazo](https://i.gyazo.com/4d08a8287dfddcfe9853d9289c3bc419.gif)](https://gyazo.com/4d08a8287dfddcfe9853d9289c3bc419)

using CM 5.42.0

**Comment by marijnh** [comment]
This looks like your editor doesn't have its final layout when it is initialized, either because style sheets (or fonts) are still loading, or because the element isn't part of the DOM and/or hidden at that time. Call `refresh` when the editor is visible and its layout stable to make it re-measure its size and fix this.

**Comment by NoFishLikeIan** [comment]
It is a bit late but a potential solution is to use the [documents fonts](https://developer.mozilla.org/en-US/docs/Web/API/Document/fonts) api and then call `refresh` as suggested by @marijnh
