### ISSUE TITLE
selecting text with mouse does not work in macos Safari and JavaFX WebView component

### ISSUE THREAD

**Issue by xzel23** [codemirror/CodeMirror#5733]
## Problem

When CodeMirror is displayed inside a JavaFX WebView, text cannot be selected using the mouse. The cursor moves to the correct position and then stays there when the mouse is moved. Selecting words using double click works as expected.

## Details

- CodeMirror: version 5.38.0 and above, version 5.37.0 still works as expected
- Browser: JavaFX WebView Component, tested in version 8 and 11, and 12 EA

## Cause of problem

In version 5.38.0 of codemirror.js line 7501 changed from

    if (!e_button(e)) { done(e); }

to

    if (e.buttons === 0 || !e_button(e)) { done(e); }

and once more in mouse_events.js line 316 (this time without curly braces.

If I change both lines back to the 5.37.0 version, everything works as expected.

Please evaluate if this is something that should be fixed in WebView instead so that I can report it there.

**Comment by firasdib** [comment]
This issue seems to be related to: https://github.com/firasdib/Regex101/issues/1085

**Comment by firasdib** [comment]
False alarm on my part.

**Comment by xzel23** [comment]
Same happens in Safari (Version 12.1.1 on macOS Mojave). As no-one seems to be interested in supporting the WebView component, I changed the title. Hope this gets some more traction.

Since it also happens in Safari, fixing in WebView (as I previously suggested) doesn't seem to be the right approach.

**Comment by xzel23** [comment]
OK, after I made some changes, I cannot reproduce on Safari, but the problem persists in WebView. When I find the time, I will dig deeper. But for now, I just downgraded to 5.37.0. I will close this, as there's not much you can do at the moment.

**Comment by cnanjo** [comment]
I ran into the exact same issue with WebView and saw this post. I reverted those two lines and it now works for me. Any fix on the horizon for this item? A number of us are using JavaFX and a fix would be great.

**Comment by FranzDeschler** [comment]
I have the exact same issue.
I could reproduce it with JavaFX 17.0.2. The workaround works great.
The WebKit version which is used in JavaFX WebView doesn´t seem to support [MouseEvent.buttons](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons)
It should provide the mouse-buttons which were pressed. Since it always returns 0 CodeMirror thinks no mouse button is pressed and canceles the operation.

I hope this will be supported in the future in JavaFX.
For now we need to live with one of these workarounds:
`if (!e_button(e)) { done(e); }`
Or replace `||` with `&&`:
`if (e.buttons === 0 && !e_button(e)) { done(e); }`
