### ISSUE TITLE
No syntax highlighting for Scala's string interpolation 

### ISSUE THREAD

**Issue by xavierguihot** [codemirror/CodeMirror#5831]
In `Scala`, [string interpolation](https://docs.scala-lang.org/overviews/core/string-interpolation.html) is highlighted as a simple string.

By string interpolation, I mean this kind of things (here in Scala):

```scala
val hello = "Hello"
val world = "World"
s"$hello $world!"
```

Note how the string interpolation part of this snippet is not highlighted by  github, as opposed to the examples in the [link above (scala's documentation)](https://docs.scala-lang.org/overviews/core/string-interpolation.html).

**Comment by marijnh** [comment]
Yes, this is a feature that doesn't seem to be implemented in the Scala mode, which is a simple configuration of the clike mode. It is unlikely to get added by the core team, since the contributed modes are only minimally maintained at this point, so I'm not going to keep this issue open. But if you want to submit a pull request that addresses this, that'd be welcome.
