### ISSUE TITLE
Multiline typescript generics highlightning

### ISSUE THREAD

**Issue by goodmind** [codemirror/CodeMirror#5921]
```ts
const foo = createEffect<{foo: number}>()
const bar = createEffect<{
  foo: number
}>()
```

This works for one line, but doesn't work for multiple lines

**Comment by marijnh** [comment]
There's an ambiguity in the TypeScript grammar where you can't tell whether something is a less-than or a type argument list until you've seen whether there are call parens after it. Since CodeMirror modes can't (conveniently) do that kind of arbitrary lookahead, not supporting this is an intentional decision for the time being.
