### ISSUE TITLE
Shift-Delete in Firefox on PC

### ISSUE THREAD

**Issue by tophf** [codemirror/CodeMirror#6061]
When nothing is selected a [standard PC shortcut](https://en.wikipedia.org/wiki/Cut,_copy,_and_paste#Common_keyboard_shortcuts) <kbd>Shift</kbd><kbd>Delete</kbd> cuts the entire line(s), but Firefox only implements this behavior on Ctrl-Insert (and of course on Ctrl-X, Ctrl-C), which certainly looks like a bug.

I think it would make sense for CodeMirror to add the missing functionality in Firefox on PC:
```js
if (gecko && !mac && document.execCommand) {
  CodeMirror.keyMap.pcDefault['Shift-Delete'] = 'cutToClipboardSelOrLine';
  CodeMirror.commands.cutToClipboardSelOrLine = cm => {
    if (cm.somethingSelected()) {
      document.execCommand('cut');
      return;
    }
    cm.setSelections(
      cm.listSelections()
      .map(({ anchor: { line } }) => ({
        anchor: { line, ch: 0 },
        head: { line: line + 1, ch: 0 },
      })),
    );
    Promise.resolve().then(() => document.execCommand('cut'));
  };
}
```
I've used Promise to postpone execCommand because I don't know how to utilize CodeMirror's internal methods properly.

**Comment by marijnh** [comment]
Since this is more of a kludge than a proper keybinding (and defining it as a command isn't a good idea when it's only going to be available in some situations), attached patch adds it to the keydown handler instead. It also simplifies the change by letting the existing cut event handler take care of the linewise logic. Does that work for you?

**Comment by tophf** [comment]
Yeah it works and the solution is absolutely amazing in its terseness, thanks.
