### ISSUE TITLE
Running Jest get TypeError: CodeMirror.MergeView is not a function

### ISSUE THREAD

**Issue by ritchiea** [codemirror/CodeMirror#6172]
I have the import

```
import * as CodeMirror from 'codemirror';
import 'codemirror/addon/merge/merge';
```

I'm using Vue.js & Typescript, it works fine in my Vue component. But writing a basic Jest test when I mount the component in Jest `const wrapper = mount(Component)` I get this error:

```  
   console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
    [Vue warn]: Error in mounted hook: "TypeError: CodeMirror.MergeView is not a function"

    found in

    ---> <Anonymous>
           <Root>

  console.error node_modules/vue/dist/vue.runtime.common.dev.js:1884
    TypeError: CodeMirror.MergeView is not a function
```

**Comment by marijnh** [comment]
One thing that might be going on is that whatever bundler is running is creating multiple instances of the main CodeMirror library because it fails to unify different relative imports. You can check for that by adding a temporary log statement to the top level of lib/codemirror.js and seeing if it gets run multiple times.

In any case, this is an integration issue in another tool, not something that belongs on this issue tracker.
