### ISSUE TITLE
Visible line widget height ignored as cursor goes outside editor when DOM element rendered by React

### ISSUE THREAD

**Issue by Pet3ris** [codemirror/CodeMirror#6359]
Hi There,

This is just a mirror of the issue discussed in the forum: https://discuss.codemirror.net/t/potential-bug-code-mirror-line-widget-above-the-first-line-disturbs-cursor-location/2535/2.

A line widget added to the editor distorts the cursor position (as if the line widget wasn't there).

Here is the problem reproduced:
https://codesandbox.io/s/loving-hodgkin-30t2x?file=/src/App.js

It goes away only after starting to type in the editor (but I haven't found any way or workaround to remove this effect programmatically).

![image](https://user-images.githubusercontent.com/224585/88548087-848e5600-d016-11ea-87ca-c18dff884d1b.png)

^ as you see here, the cursor is placed inside the line widget rather than the editor lines.

**Comment by Pet3ris** [comment]
Also - would really love to hear if anyone has an idea for a hacky work-around that we could use to ship the feature for the meantime.

**Comment by marijnh** [comment]
The problem is that you're using react to render the widget content. When `addLineWidget` is called, the `<div>` is still empty, and has no height. You'll want to either use plain DOM to create the widget, delay the call to `addLineWidget` until it has been rendered by react, or schedule a call to `widget.changed()` when it finishes rendering, otherwise the editor won't be able to measure the widget height.

**Comment by Pet3ris** [comment]
Thanks a lot @marijnh, was able to update this and it works now. Turns out the ReasonML API doesn't show the callback argument so I assumed the render was synchronous! My bad.
