### ISSUE TITLE
Searching with a bad regexp causes codemirror search cursor to hang

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#6361]
1. Open https://codemirror.net/demo/search.html
2. Cmd+F
3. Search for `/(.|\s)*?;/gim`

Expected: Search would find something or nothing

Actual: The tab hangs or crashes

**Comment by marijnh** [comment]
If you run this regexp on a string of some length directly, you also hang your JS interpreter. It's a highly exponential regexp, and I don't think CodeMirror can be held responsible for the regexp engine's running behavior. (It would be nice if it could cut off such long-running matches, but since the JS regexp interface doesn't provide a way to do that, and implementing our own regexp matcher seems like a bad idea, I don't see much possibilities there).
