### ISSUE TITLE
High amount of lines cause slow rendering in chrome due autoresize feature

### ISSUE THREAD

**Issue by franciscorode** [codemirror/CodeMirror#6364]
Hello!

We have noticed a slow perform rendering in codemirror instances with autoresize enabled and hight amount of lines in chrome, and imagine based browsers in chrome render engine, in comparision with other browsers like firefox

I was following this issue around recalculating of CSS  in react implementation https://github.com/styleguidist/react-styleguidist/issues/86

The low perform is reproduced to a lesser extent in codemirror autoresize demo pasting high amount of lines https://codemirror.net/demo/resize.html

We would like to keep the autoresize feature displaying a large number of lines, has anyone had the same or similar problem, any idea or alternative to minimize the problem?

**Comment by marijnh** [comment]
This is the expected behavior—when autosizing, the editor will draw all its content to the DOM, which will be expensive when there's a lot of it. The rewrite for [version 6](https://github.com/codemirror/codemirror.next/) will address this (basing its drawing on the window viewport), but it is unlikely to be solved in the 5.x code.
