### ISSUE TITLE
editor.save() do not replace textarea value on paste event.

### ISSUE THREAD

**Issue by Bogdan1001** [codemirror/CodeMirror#6378]
Hello, 

When I enter text to codemirror manually - it correctly updates the textarea.

But when I try to paste some value to codemirror - I do not fetch any update in `editor.save(text)`. At the same time, in `console.log(text)`, I can see the pasted value in the console.

What am I doing wrong?

```
const editor = CodeMirror.fromTextArea(document.getElementById('cm_textarea'),
    {
      mode: "text/html",
      lineNumbers: true,
      theme: "material"
    });

    editor.on('change', (editor) => {
      const text = editor.getValue()
      console.log(text)
      editor.save(text)
    })
```

**Comment by marijnh** [comment]
>  I do not fetch any update in editor.save(text)

What's `text`? The `save` method doesn't take any arguments.

**Comment by jdbruxelles** [comment]
Hi, I can't reproduce the issue. I made a [test](https://code.wetrafa.xyz/?code=IjxzY3JpcHQgc3JjPVwiaHR0cHM6Ly9jZG5qcy5jbG91ZGZsYXJlLmNvbS9hamF4L2xpYnMvY29kZW1pcnJvci81LjU2LjAvY29kZW1pcnJvci5taW4uanNcIj48L3NjcmlwdD5cbjxsaW5rIHJlbD1cInN0eWxlc2hlZXRcIiBocmVmPVwiaHR0cHM6Ly9jZG5qcy5jbG91ZGZsYXJlLmNvbS9hamF4L2xpYnMvY29kZW1pcnJvci81LjU2LjAvY29kZW1pcnJvci5taW4uY3NzXCIvPlxuXG48dGV4dGFyZWEgaWQ9XCJjbV90ZXh0YXJlYVwiPjwvdGV4dGFyZWE%2BXG48cD48L3A%2BXG5cbjxzY3JpcHQ%2BXG5cdGNvbnN0IGVkaXRvciA9IENvZGVNaXJyb3IuZnJvbVRleHRBcmVhKGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdjbV90ZXh0YXJlYScpLCB7XG4gICAgbW9kZTogXCJ0ZXh0L2h0bWxcIixcbiAgICBsaW5lTnVtYmVyczogdHJ1ZVxuICB9KTtcblxuXHRjb25zdCBwID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcihcInBcIik7XG4gIGVkaXRvci5vbignY2hhbmdlJywgKGVkaXRvcikgPT4ge1xuICAgIGNvbnN0IHRleHQgPSBlZGl0b3IuZ2V0VmFsdWUoKVxuICAgIGNvbnNvbGUubG9nKHRleHQpO1xuICAgIHAuaW5uZXJUZXh0ID0gdGV4dDtcbiAgICBlZGl0b3Iuc2F2ZSgpO1xuICB9KTtcbjwvc2NyaXB0PiI%253D&fname=Q29kZU1pcnJyb3IgZGVtby5odG1s&exe=1&ref=share_as_code), but when I paste some text in the editor, all is updated correctly with the change event. I think the problem is not there.

> What's text?

The value of the editor.

**Comment by Bogdan1001** [comment]
I see, thanks, then it looks like the issue on the Phoenix Live View - the framework that I use.
