### ISSUE TITLE
Cannot change inputStyle

### ISSUE THREAD

**Issue by tylershuster** [codemirror/CodeMirror#6446]
https://github.com/codemirror/CodeMirror/blob/2571b4ad08e007c246d73bdd973892bf5dd7b02e/src/edit/options.js#L78

Any idea when this will be fixed? Or if there are no plans, is there any documentation on why this is the way that it is?

**Comment by marijnh** [comment]
Support for this won't be added anymore. There's quite a bit of editor state that works differently depending on the input style, and the work to wire up everything to update when changing input styles was never done. Since focus is now on the upcoming version 6 (which is always contentEditable-based), I don't have plans to do further work on this feature.
