### ISSUE TITLE
Focus lost when clicked on already focused editor area in MS Edge browser

### ISSUE THREAD

**Issue by vikasjagtap** [codemirror/CodeMirror#6579]
In MS Edge browser when clicked on already focused editor the focus is lost and clicking on the editor afterwards does not focus it again. To gain focus you have to click outside of the codemirror and then click again on the editor. 

This behaviour can be seen with the example shown on the codemirror home page.

**Comment by marijnh** [comment]
Which version of Edge are you using?

**Comment by vikasjagtap** [comment]
> Which version of Edge are you using?

Microsoft Edge 44.19041.423.0
Microsoft EdgeHTML 18.19041

Thanks

**Comment by marijnh** [comment]
I haven't found a way to install Edge 44, and since this problem isn't huge and that browser is legacy at this point, I don't intend to further look into this.

**Comment by jonasnordlund** [comment]
This scenario happens if you use this component in a Windows UWP application combined with the `WebView` control which defaults to this legacy EdgeHTML rendering engine. But you're correct that one should probably not spend time on this issue. Microsoft wants us to code WinUI 3 apps nowadays and these will use the WebView2 component that uses the Chromium-based engine.

Just adding this comment for some additional search keywords.
