### ISSUE TITLE
Codemirror is vulnerable to a regular expression denial of service attack

### ISSUE THREAD

**Issue by micmcg** [codemirror/CodeMirror#6591]
https://sca.analysiscenter.veracode.com/vulnerability-database/security/regular-expression-denial-of-service-redos-/javascript/sid-29274

> codemirror is vulnerable to regular expression denial of service. An attacker is able to cause a denial of service condition by passing long strings containing sub-pattern `(s|/*.*?*/)*`.

I'm sorry I don't have more information for a reproduction case, this was the result of running automated vulnerability scanning software against our codebase

**Comment by marijnh** [comment]
I assume this has been reported and already fixed. But indeed, since that page provides no useful details, I'm not sure which problem it is talking about. A few of these have been fixed in the past months, and since people don't tend to create advisories without notifying the maintainers, I'm going to assume this is nothing new.
