### ISSUE TITLE
Tutorial step by step for beginners

### ISSUE THREAD

**Issue by me-suzy** [codemirror/CodeMirror#6691]
hello. I check the informations from here https://codemirror.net/6/examples/styling/  but I didn't understand completly.

For example, I have this code in File.html

```
def func(A):
    result = 0
    n = len(A)
    while n > 1:
        n = n/2
        result = result + min(A[1,...,n])
    return result
```

So, I import the css style in the `<head>` section:

```
    <link rel="stylesheet" href="codemirror.min.css">
    <link rel="stylesheet" type="text/css" href="./theme/abcdef.css">
    <script src="runmode-standalone.min.js"></script>
    <script src="python.min.js"></script>
```

Ok, now I have imported the css and the code that I want to frame it in the **abcdef.css** from folder theme.

For this, should I must select the code and choose a css class from it ? Because I try this and it's not working.

**Comment by marijnh** [comment]
You appear to be mixing documentation for version 5 (which that HTML is based on) with version 6 (the link). The manual for codemirror 5 is at https://codemirror.net/doc/manual.html, and the [`"theme"` option](https://codemirror.net/doc/manual.html#option_theme) is what you use to enable a theme.

**Comment by marijnh** [comment]
No, that's not it at all. This library won't convert a `<pre>` tag to an editor for you. If you want to use a theme, you'll need to create an editor. The manual describes how to do that. You'll have to write JavaScript, not just HTML.

More generally, please use the [forum](https://discuss.codemirror.net/) instead of the bugtracker to ask question.
