### ISSUE TITLE
Safari spellcheck corrections are sometimes reverted

### ISSUE THREAD

**Issue by psalaets** [codemirror/CodeMirror#6733]
# Summary

In a CM 5 instance with the `spellcheck: true` option, some spelling corrections are reverted immediately after they are applied by the browser.

# Versions

- CodeMirror 5.62.0
- Safari 14.1.1
- macOS 11.4

*Problem not seen in Firefox (mac), Chrome (mac), Edge (windows)*

# Video showing problem

https://www.youtube.com/watch?v=Jq53DUxuGUY

# Code Demo

https://codepen.io/psalaets/pen/vYmNOJb

# Additional details

I don't know enough about CM internals to know what this means, but it seemed like `ContentEditableInput.prototype.pollContent` returned `undefined` in the cases where the bug occurred. When the typo correction was applied successfully `ContentEditableInput.prototype.pollContent` returned `true`.

**Comment by Billiam** [comment]
Also occurring in chrome. 

I Just spent some time debugging this in my own app. 

When it happens, pollContent() fails the last check (`newText.length > 1 || newText[0] || cmp(chFrom, chTo`), so no content is replaced. 

The issue appears to be that pollContent is based on the primary cursor selection, and that selection can refer to another area of the document, not at the spellcheck replacement location.

I _think_ this won't occur in text inputs (only in contenteditable), because there's an option (resetSelectionOnContextMenu, enabled by default) that will move the cursor to the spellcheck location before spellcheck fires the `input`->`insertReplacementText` event.

This workaround seems to work for me. Does it work in safari as well?

Set the cursor position on contextmenu so that the dom poll event works:
https://codepen.io/billiam/pen/XWRjqzY

**Comment by psalaets** [comment]
Thanks for sharing your findings.

> Does it work in safari as well?

With the workaround in place Safari no longer shows spelling suggestions in the context menu.

It seems like the cursor movement causes Safari to lose track of what word was right-clicked. The context menu is also missing the "Look Up &lt;word&gt;" and "Search with Google" options that it usually has.

**Comment by Billiam** [comment]
How about this?

https://codepen.io/billiam/pen/JjNRqzK

**Comment by psalaets** [comment]
That's working! Sweet. Thanks for taking time out of your weekend to look at this.

I'm closing this issue because there is a workaround.
