### ISSUE TITLE
"CodeMirror-selected" class isn't added to most recent selection in contenteditable mode

### ISSUE THREAD

**Issue by Billiam** [codemirror/CodeMirror#6774]
**Description**: In contenteditable mode, the `CodeMirror-selected` class is only applied when creating multiple selections (ex: by control clicking), and then is only added to the oldest selections.

When Using a textarea editor, the class is applied for each selection correctly.

**Version**: 5.62.3
**Steps**:

With an editor using inputStyle: 'contenteditable', and a style on `.CodeMirror-selected`

1. Select text

The `CodeMirror-selected` element is not added.

2. Control click to select additional text

The `CodeMirror-selected` class is now added to the first selection, but not to the most recent one.

**Demo**: https://codepen.io/billiam/pen/xxrEPeo

**Comment by marijnh** [comment]
This is how it is intended to work—`CodeMirror-selected` isn't actually applied to text content in the editor at all, but is used in the backdrop elements that provide a background color for the selection. Since contenteditable mode uses the native selection for the primary selection, that range doesn't get a backdrop. You may want the [mark-selection](https://codemirror.net/doc/manual.html#addon_mark-selection) addon here, which does add a style to selected text.

**Comment by Billiam** [comment]
Got it, thank you
