### ISSUE TITLE
Stupid question : how do you start using it ?

### ISSUE THREAD

**Issue by Klemich** [codemirror/CodeMirror#6783]
Hi, 

So now it's officially installed on the ubuntu server
![image](https://user-images.githubusercontent.com/16766404/134671889-37d76dec-4997-4a33-8061-dc3a15ed179c.png)

But, how do I access it >< ? I'm a bit n00b, sorry for that. Do I need to setup an application file for ufw ? DO I need to setup a server  block on nginx conf files ?
Thanks

**Comment by marijnh** [comment]
This is a JavaScript library, not an application that you can install and start editing with. It assumes a basic proficiency with JavaScript and the package management used in the JavaScript ecosystem. This is not the place to get help on those things.

**Comment by Klemich** [comment]
Thanks. 
That would be great to participate in developping opensource free and nice tools like this one for non pro coders like me. 
Do you have any idea where I can find how to create the text editor using codemirror ?

**Comment by marijnh** [comment]
The website has some [examples](https://codemirror.net/6/examples/) that might help you figure out how to set it up. Participating in development without much coding experience is going to be difficult, since there's little work involved that doesn't require a solid understanding of the software, sorry.
